<#assign classbody>
<!DOCTYPE databases PUBLIC 
  "-//EXOLAB/Castor Mapping DTD Version 1.0//EN"
  "http://castor.exolab.org/mapping.dtd">
<mapping>
  <description>Generated By Hibernate Tool</description>

  <#foreach entity in c2j.getPOJOIterator(cfg.getClassMappings())>
  
  <class name="${entity.qualifiedDeclarationName}">
    <map-to xml="${c2j.lowerFirstLetter(entity.declarationName)}"/>

    <#foreach field in entity.allPropertiesIterator>
    
    <#if c2j.isCollection(field)>
    <field name="${field.name}" type="${c2j.getJavaTypeNameInCollection(field, true)}" collection="collection">
      <bind-xml name="${c2j.lowerFirstLetter(c2j.getUnqualifiedName(c2j.getJavaTypeNameInCollection(field, true)))}"/>
    </field>    
    <#else>
      <#if (entity.qualifiedDeclarationName = "com.intertek.entity.CurrencyRate") && (field.name = "lastUpdateDate")>
        <field name="${field.name}" type="java.lang.String" handler="com.intertek.tool.oxm.castor.CurrencyRateLastUpdateDateFormater">
          <bind-xml name="${field.name}"/>
        </field>
      <#else>
			<#if (entity.qualifiedDeclarationName = "com.intertek.entity.BankAccount") && (field.name = "bi")>
	        	<field name="${field.name}" type="java.lang.String" handler="com.intertek.tool.oxm.castor.YesNoBooleanFormater">
	          		<bind-xml name="${field.name}"/>
	        	</field>
      		<#else>
        		<field name="${field.name}" type="${c2j.getJavaTypeName(field, true)}">
          			<bind-xml name="${field.name}"/>
        		</field>
			</#if>
      </#if>
    </#if>
      
    </#foreach>
  </class>
    
  </#foreach>

  <#foreach entity in c2j.getPOJOIterator(cfg.getClassMappings())>
  
    <#foreach field in entity.allPropertiesIterator>
    
      <#if field.composite>
        <class name="${c2j.getPOJOClass(field.value).qualifiedDeclarationName}">
          <map-to xml="${c2j.lowerFirstLetter(field.name)}"/>

          <#foreach field1 in c2j.getPOJOClass(field.value).allPropertiesIterator>

          <#if c2j.isCollection(field1)>
          <field name="${field1.name}" type="${c2j.getJavaTypeNameInCollection(field1, true)}" collection="collection">
            <bind-xml name="${c2j.lowerFirstLetter(c2j.getUnqualifiedName(c2j.getJavaTypeNameInCollection(field1, true)))}"/>
          </field>    
          <#else>
          <field name="${field1.name}" type="${c2j.getJavaTypeName(field1, true)}">
            <bind-xml name="${field1.name}"/>
          </field>
          </#if>

          </#foreach>

        </class>
      </#if>
      
    </#foreach>
    
  </#foreach>

</mapping>

</#assign>

${classbody}
