package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * BankAccountCurr generated by hbm2java
 */
public class BankAccountCurr  implements java.io.Serializable {

    // Fields    

     private BankAccountCurrId bankAccountCurrId;
     private Boolean primary;

     // Constructors

    /** default constructor */
    public BankAccountCurr() {
    }

	/** minimal constructor */
    public BankAccountCurr(BankAccountCurrId bankAccountCurrId) {
        this.bankAccountCurrId = bankAccountCurrId;
    }
    /** full constructor */
    public BankAccountCurr(BankAccountCurrId bankAccountCurrId, Boolean primary) {
       this.bankAccountCurrId = bankAccountCurrId;
       this.primary = primary;
    }
   
    // Property accessors
    public BankAccountCurrId getBankAccountCurrId() {
        return this.bankAccountCurrId;
    }
    
    public void setBankAccountCurrId(BankAccountCurrId bankAccountCurrId) {
        this.bankAccountCurrId = bankAccountCurrId;
    }
    public Boolean getPrimary() {
        return this.primary;
    }
    
    public void setPrimary(Boolean primary) {
        this.primary = primary;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BankAccountCurr) ) return false;
		 BankAccountCurr castOther = ( BankAccountCurr ) other; 
         
		 return ( (this.getBankAccountCurrId()==castOther.getBankAccountCurrId()) || ( this.getBankAccountCurrId()!=null && castOther.getBankAccountCurrId()!=null && this.getBankAccountCurrId().equals(castOther.getBankAccountCurrId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBankAccountCurrId() == null ? 0 : this.getBankAccountCurrId().hashCode() );
         
         return result;
   }   


}


