package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * BranchLanguage generated by hbm2java
 */
public class BranchLanguage  implements java.io.Serializable {

    // Fields    

     private BranchLanguageId branchLanguageId;
     private String description;
     private String address1;
     private String address2;
     private String address3;
     private String address4;
     private String city;
     private String county;
     private String postal;
     private String companyDesc;
     private Branch branch;

     // Constructors

    /** default constructor */
    public BranchLanguage() {
    }

	/** minimal constructor */
    public BranchLanguage(BranchLanguageId branchLanguageId) {
        this.branchLanguageId = branchLanguageId;
    }
    /** full constructor */
    public BranchLanguage(BranchLanguageId branchLanguageId, String description, String address1, String address2, String address3, String address4, String city, String county, String postal, String companyDesc, Branch branch) {
       this.branchLanguageId = branchLanguageId;
       this.description = description;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.address4 = address4;
       this.city = city;
       this.county = county;
       this.postal = postal;
       this.companyDesc = companyDesc;
       this.branch = branch;
    }
   
    // Property accessors
    public BranchLanguageId getBranchLanguageId() {
        return this.branchLanguageId;
    }
    
    public void setBranchLanguageId(BranchLanguageId branchLanguageId) {
        this.branchLanguageId = branchLanguageId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }
    public String getAddress4() {
        return this.address4;
    }
    
    public void setAddress4(String address4) {
        this.address4 = address4;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCounty() {
        return this.county;
    }
    
    public void setCounty(String county) {
        this.county = county;
    }
    public String getPostal() {
        return this.postal;
    }
    
    public void setPostal(String postal) {
        this.postal = postal;
    }
    public String getCompanyDesc() {
        return this.companyDesc;
    }
    
    public void setCompanyDesc(String companyDesc) {
        this.companyDesc = companyDesc;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BranchLanguage) ) return false;
		 BranchLanguage castOther = ( BranchLanguage ) other; 
         
		 return ( (this.getBranchLanguageId()==castOther.getBranchLanguageId()) || ( this.getBranchLanguageId()!=null && castOther.getBranchLanguageId()!=null && this.getBranchLanguageId().equals(castOther.getBranchLanguageId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBranchLanguageId() == null ? 0 : this.getBranchLanguageId().hashCode() );
         
         
         
         
         
         
         
         
         
         
         return result;
   }   


}


