package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * BranchInt generated by hbm2java
 */
public class BranchInt  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=8) private String branchName;
     private Boolean samInd;
     private Boolean limsInd;
     private Branch branch;

     // Constructors

    /** default constructor */
    public BranchInt() {
    }

	/** minimal constructor */
    public BranchInt(String branchName) {
        this.branchName = branchName;
    }
    /** full constructor */
    public BranchInt(String branchName, Boolean samInd, Boolean limsInd, Branch branch) {
       this.branchName = branchName;
       this.samInd = samInd;
       this.limsInd = limsInd;
       this.branch = branch;
    }
   
    // Property accessors
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
    public Boolean getSamInd() {
        return this.samInd;
    }
    
    public void setSamInd(Boolean samInd) {
        this.samInd = samInd;
    }
    public Boolean getLimsInd() {
        return this.limsInd;
    }
    
    public void setLimsInd(Boolean limsInd) {
        this.limsInd = limsInd;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BranchInt) ) return false;
		 BranchInt castOther = ( BranchInt ) other; 
         
		 return ( (this.getBranchName()==castOther.getBranchName()) || ( this.getBranchName()!=null && castOther.getBranchName()!=null && this.getBranchName().equals(castOther.getBranchName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBranchName() == null ? 0 : this.getBranchName().hashCode() );
         
         
         
         return result;
   }   


}


