package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * BusStream generated by hbm2java
 */
public class BusStream  implements java.io.Serializable {

    // Fields    

     private BusStreamId busStreamId;
     private Integer sortOrderNum;
     private Branch branch;

     // Constructors

    /** default constructor */
    public BusStream() {
    }

	/** minimal constructor */
    public BusStream(BusStreamId busStreamId) {
        this.busStreamId = busStreamId;
    }
    /** full constructor */
    public BusStream(BusStreamId busStreamId, Integer sortOrderNum, Branch branch) {
       this.busStreamId = busStreamId;
       this.sortOrderNum = sortOrderNum;
       this.branch = branch;
    }
   
    // Property accessors
    public BusStreamId getBusStreamId() {
        return this.busStreamId;
    }
    
    public void setBusStreamId(BusStreamId busStreamId) {
        this.busStreamId = busStreamId;
    }
    public Integer getSortOrderNum() {
        return this.sortOrderNum;
    }
    
    public void setSortOrderNum(Integer sortOrderNum) {
        this.sortOrderNum = sortOrderNum;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BusStream) ) return false;
		 BusStream castOther = ( BusStream ) other; 
         
		 return ( (this.getBusStreamId()==castOther.getBusStreamId()) || ( this.getBusStreamId()!=null && castOther.getBusStreamId()!=null && this.getBusStreamId().equals(castOther.getBusStreamId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBusStreamId() == null ? 0 : this.getBusStreamId().hashCode() );
         
         
         return result;
   }   


}


