package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * CfgJobCode generated by hbm2java
 */
public class CfgJobCode  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=105) private String jobCode;
     private Integer sortOrderNum;

     // Constructors

    /** default constructor */
    public CfgJobCode() {
    }

	/** minimal constructor */
    public CfgJobCode(String jobCode) {
        this.jobCode = jobCode;
    }
    /** full constructor */
    public CfgJobCode(String jobCode, Integer sortOrderNum) {
       this.jobCode = jobCode;
       this.sortOrderNum = sortOrderNum;
    }
   
    // Property accessors
    public String getJobCode() {
        return this.jobCode;
    }
    
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }
    public Integer getSortOrderNum() {
        return this.sortOrderNum;
    }
    
    public void setSortOrderNum(Integer sortOrderNum) {
        this.sortOrderNum = sortOrderNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CfgJobCode) ) return false;
		 CfgJobCode castOther = ( CfgJobCode ) other; 
         
		 return ( (this.getJobCode()==castOther.getJobCode()) || ( this.getJobCode()!=null && castOther.getJobCode()!=null && this.getJobCode().equals(castOther.getJobCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getJobCode() == null ? 0 : this.getJobCode().hashCode() );
         
         return result;
   }   


}


