package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * Contract generated by hbm2java
 */
public class Contract  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=15) private String contractCode;
     @Length(min=0, max=4) private String status;
     @NotBlank  @Length(min=0, max=512) private String description;
     @Length(min=0, max=32) private String workingUOM;
     @Length(min=0, max=32) private String workingPB;
     private Date masterListDate;
     @Length(min=0, max=32) private String invoiceType;
     private Date statusDate;
     private Date expireDate;
     @Length(min=0, max=128) private String signatoryUserName;
     private User signatory;
     @Length(min=0, max=128) private String originatorUserName;
     private User originator;
     @Length(min=0, max=32) private String paymentTermsCD;
     private Date createdTime;
     @Length(min=0, max=128) private String creByUserName;
     private Date updatedTime;
     @Length(min=0, max=128) private String modByUserName;
     private Set<ContractAttach> contractAttaches = new HashSet<ContractAttach>(0);
     private Set<CfgContract> cfgContracts = new HashSet<CfgContract>(0);

     // Constructors

    /** default constructor */
    public Contract() {
    }

	/** minimal constructor */
    public Contract(String contractCode) {
        this.contractCode = contractCode;
    }
    /** full constructor */
    public Contract(String contractCode, String status, String description, String workingUOM, String workingPB, Date masterListDate, String invoiceType, Date statusDate, Date expireDate, String signatoryUserName, User signatory, String originatorUserName, User originator, String paymentTermsCD, Date createdTime, String creByUserName, Date updatedTime, String modByUserName, Set<ContractAttach> contractAttaches, Set<CfgContract> cfgContracts) {
       this.contractCode = contractCode;
       this.status = status;
       this.description = description;
       this.workingUOM = workingUOM;
       this.workingPB = workingPB;
       this.masterListDate = masterListDate;
       this.invoiceType = invoiceType;
       this.statusDate = statusDate;
       this.expireDate = expireDate;
       this.signatoryUserName = signatoryUserName;
       this.signatory = signatory;
       this.originatorUserName = originatorUserName;
       this.originator = originator;
       this.paymentTermsCD = paymentTermsCD;
       this.createdTime = createdTime;
       this.creByUserName = creByUserName;
       this.updatedTime = updatedTime;
       this.modByUserName = modByUserName;
       this.contractAttaches = contractAttaches;
       this.cfgContracts = cfgContracts;
    }
   
    // Property accessors
    public String getContractCode() {
        return this.contractCode;
    }
    
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getWorkingUOM() {
        return this.workingUOM;
    }
    
    public void setWorkingUOM(String workingUOM) {
        this.workingUOM = workingUOM;
    }
    public String getWorkingPB() {
        return this.workingPB;
    }
    
    public void setWorkingPB(String workingPB) {
        this.workingPB = workingPB;
    }
    public Date getMasterListDate() {
        return this.masterListDate;
    }
    
    public void setMasterListDate(Date masterListDate) {
        this.masterListDate = masterListDate;
    }
    public String getInvoiceType() {
        return this.invoiceType;
    }
    
    public void setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType;
    }
    public Date getStatusDate() {
        return this.statusDate;
    }
    
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
    public String getSignatoryUserName() {
        return this.signatoryUserName;
    }
    
    public void setSignatoryUserName(String signatoryUserName) {
        this.signatoryUserName = signatoryUserName;
    }
    public User getSignatory() {
        return this.signatory;
    }
    
    public void setSignatory(User signatory) {
        this.signatory = signatory;
    }
    public String getOriginatorUserName() {
        return this.originatorUserName;
    }
    
    public void setOriginatorUserName(String originatorUserName) {
        this.originatorUserName = originatorUserName;
    }
    public User getOriginator() {
        return this.originator;
    }
    
    public void setOriginator(User originator) {
        this.originator = originator;
    }
    public String getPaymentTermsCD() {
        return this.paymentTermsCD;
    }
    
    public void setPaymentTermsCD(String paymentTermsCD) {
        this.paymentTermsCD = paymentTermsCD;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getCreByUserName() {
        return this.creByUserName;
    }
    
    public void setCreByUserName(String creByUserName) {
        this.creByUserName = creByUserName;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
    public String getModByUserName() {
        return this.modByUserName;
    }
    
    public void setModByUserName(String modByUserName) {
        this.modByUserName = modByUserName;
    }
    public Set<ContractAttach> getContractAttaches() {
        return this.contractAttaches;
    }
    
    public void setContractAttaches(Set<ContractAttach> contractAttaches) {
        this.contractAttaches = contractAttaches;
    }
    public Set<CfgContract> getCfgContracts() {
        return this.cfgContracts;
    }
    
    public void setCfgContracts(Set<CfgContract> cfgContracts) {
        this.cfgContracts = cfgContracts;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Contract) ) return false;
		 Contract castOther = ( Contract ) other; 
         
		 return ( (this.getContractCode()==castOther.getContractCode()) || ( this.getContractCode()!=null && castOther.getContractCode()!=null && this.getContractCode().equals(castOther.getContractCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getContractCode() == null ? 0 : this.getContractCode().hashCode() );
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         return result;
   }   


}


