package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ContactCustId generated by hbm2java
 */
public class ContactCustId  implements java.io.Serializable {

    // Fields    

     private long contactId;
     @NotBlank @Length(min=0, max=15) private String custCode;
     private Integer locationNumber;

     // Constructors

    /** default constructor */
    public ContactCustId() {
    }

    /** full constructor */
    public ContactCustId(long contactId, String custCode, Integer locationNumber) {
       this.contactId = contactId;
       this.custCode = custCode;
       this.locationNumber = locationNumber;
    }
   
    // Property accessors
    public long getContactId() {
        return this.contactId;
    }
    
    public void setContactId(long contactId) {
        this.contactId = contactId;
    }
    public String getCustCode() {
        return this.custCode;
    }
    
    public void setCustCode(String custCode) {
        this.custCode = custCode;
    }
    public Integer getLocationNumber() {
        return this.locationNumber;
    }
    
    public void setLocationNumber(Integer locationNumber) {
        this.locationNumber = locationNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContactCustId) ) return false;
		 ContactCustId castOther = ( ContactCustId ) other; 
         
		 return (this.getContactId()==castOther.getContactId())
 && ( (this.getCustCode()==castOther.getCustCode()) || ( this.getCustCode()!=null && castOther.getCustCode()!=null && this.getCustCode().equals(castOther.getCustCode()) ) )
 && ( (this.getLocationNumber()==castOther.getLocationNumber()) || ( this.getLocationNumber()!=null && castOther.getLocationNumber()!=null && this.getLocationNumber().equals(castOther.getLocationNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getContactId();
         result = 37 * result + ( getCustCode() == null ? 0 : this.getCustCode().hashCode() );
         result = 37 * result + ( getLocationNumber() == null ? 0 : this.getLocationNumber().hashCode() );
         return result;
   }   


}


