package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ContactCust generated by hbm2java
 */
@Entity
@IdClass(com.intertek.entity.ContactCustId.class)
public class ContactCust implements java.io.Serializable {

    // Fields    

     private ContactCustId contactCustId;
     
     @Id
     private long contactId;
     @Id
     private String custCode;
     
     
     @ManyToOne
     @JoinColumn(name = "CUST_CODE")
     private Customer customer;
     
     @ManyToOne
     @JoinColumn(name = "CONTACT_ID")
     private Contact contact;
     
     
     private CustAddrSeq custAddrSeq;
     @Length(min=0, max=1) private String status;
     private Integer contactSeqNum;
     @NotBlank @Length(min=0, max=1) private String billTo;
     @NotBlank @Length(min=0, max=1) private String soldTo;
     @NotBlank @Length(min=0, max=1) private String shipTo;

     // Constructors

    /** default constructor */
    public ContactCust() {
    }

	/** minimal constructor */
    public ContactCust(ContactCustId contactCustId) {
        this.contactCustId = contactCustId;
    }
    /** full constructor */
    public ContactCust(ContactCustId contactCustId, Customer customer, Contact contact, CustAddrSeq custAddrSeq, String status, Integer contactSeqNum, String billTo, String soldTo, String shipTo) {
       this.contactCustId = contactCustId;
       this.customer = customer;
       this.contact = contact;
       this.custAddrSeq = custAddrSeq;
       this.status = status;
       this.contactSeqNum = contactSeqNum;
       this.billTo = billTo;
       this.soldTo = soldTo;
       this.shipTo = shipTo;
    }
   
    // Property accessors
    public ContactCustId getContactCustId() {
        return this.contactCustId;
    }
    
    public void setContactCustId(ContactCustId contactCustId) {
        this.contactCustId = contactCustId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public CustAddrSeq getCustAddrSeq() {
        return this.custAddrSeq;
    }
    
    public void setCustAddrSeq(CustAddrSeq custAddrSeq) {
        this.custAddrSeq = custAddrSeq;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Integer getContactSeqNum() {
        return this.contactSeqNum;
    }
    
    public void setContactSeqNum(Integer contactSeqNum) {
        this.contactSeqNum = contactSeqNum;
    }
    public String getBillTo() {
        return this.billTo;
    }
    
    public void setBillTo(String billTo) {
        this.billTo = billTo;
    }
    public String getSoldTo() {
        return this.soldTo;
    }
    
    public void setSoldTo(String soldTo) {
        this.soldTo = soldTo;
    }
    public String getShipTo() {
        return this.shipTo;
    }
    
    public void setShipTo(String shipTo) {
        this.shipTo = shipTo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContactCust) ) return false;
		 ContactCust castOther = ( ContactCust ) other; 
         
		 return ( (this.getContactCustId()==castOther.getContactCustId()) || ( this.getContactCustId()!=null && castOther.getContactCustId()!=null && this.getContactCustId().equals(castOther.getContactCustId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getContactCustId() == null ? 0 : this.getContactCustId().hashCode() );
         
         
         
         
         
         
         
         
         return result;
   }

@Id public long getContactId() {
	return contactId;
}

public void setContactId(long contactId) {
	this.contactId = contactId;
}

@Id public String getCustCode() {
	return custCode;
}

public void setCustCode(String custCode) {
	this.custCode = custCode;
}   


}


