package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ContractAttach generated by hbm2java
 */
public class ContractAttach  implements java.io.Serializable {

    // Fields    

     private long id;
     @NotBlank @Length(min=0, max=128) private String fileName;
     @NotBlank @Length(min=0, max=128) private String systemFileName;
     @NotBlank @Length(min=0, max=4) private String attachType;
     @NotBlank @Length(min=0, max=128) private String attachDescr;
     @NotBlank @Length(min=0, max=4) private String audience;
     private Date dateTimeAdded;
     @Length(min=0, max=128) private String addedByUserName;
     private User addedBy;
     @NotBlank @Length(min=0, max=15) private String contractCode;
     private Contract contract;

     // Constructors

    /** default constructor */
    public ContractAttach() {
    }

	/** minimal constructor */
    public ContractAttach(String fileName, String systemFileName, String attachType, String attachDescr, String audience, String contractCode) {
        this.fileName = fileName;
        this.systemFileName = systemFileName;
        this.attachType = attachType;
        this.attachDescr = attachDescr;
        this.audience = audience;
        this.contractCode = contractCode;
    }
    /** full constructor */
    public ContractAttach(String fileName, String systemFileName, String attachType, String attachDescr, String audience, Date dateTimeAdded, String addedByUserName, User addedBy, String contractCode, Contract contract) {
       this.fileName = fileName;
       this.systemFileName = systemFileName;
       this.attachType = attachType;
       this.attachDescr = attachDescr;
       this.audience = audience;
       this.dateTimeAdded = dateTimeAdded;
       this.addedByUserName = addedByUserName;
       this.addedBy = addedBy;
       this.contractCode = contractCode;
       this.contract = contract;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getSystemFileName() {
        return this.systemFileName;
    }
    
    public void setSystemFileName(String systemFileName) {
        this.systemFileName = systemFileName;
    }
    public String getAttachType() {
        return this.attachType;
    }
    
    public void setAttachType(String attachType) {
        this.attachType = attachType;
    }
    public String getAttachDescr() {
        return this.attachDescr;
    }
    
    public void setAttachDescr(String attachDescr) {
        this.attachDescr = attachDescr;
    }
    public String getAudience() {
        return this.audience;
    }
    
    public void setAudience(String audience) {
        this.audience = audience;
    }
    public Date getDateTimeAdded() {
        return this.dateTimeAdded;
    }
    
    public void setDateTimeAdded(Date dateTimeAdded) {
        this.dateTimeAdded = dateTimeAdded;
    }
    public String getAddedByUserName() {
        return this.addedByUserName;
    }
    
    public void setAddedByUserName(String addedByUserName) {
        this.addedByUserName = addedByUserName;
    }
    public User getAddedBy() {
        return this.addedBy;
    }
    
    public void setAddedBy(User addedBy) {
        this.addedBy = addedBy;
    }
    public String getContractCode() {
        return this.contractCode;
    }
    
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode;
    }
    public Contract getContract() {
        return this.contract;
    }
    
    public void setContract(Contract contract) {
        this.contract = contract;
    }




}


