package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ControlSwitch generated by hbm2java
 */
public class ControlSwitch  implements java.io.Serializable {

    // Fields    

     private ControlSwitchId controlSwitchId;
     @Length(min=0, max=100) private String flag;

     // Constructors

    /** default constructor */
    public ControlSwitch() {
    }

	/** minimal constructor */
    public ControlSwitch(ControlSwitchId controlSwitchId) {
        this.controlSwitchId = controlSwitchId;
    }
    /** full constructor */
    public ControlSwitch(ControlSwitchId controlSwitchId, String flag) {
       this.controlSwitchId = controlSwitchId;
       this.flag = flag;
    }
   
    // Property accessors
    public ControlSwitchId getControlSwitchId() {
        return this.controlSwitchId;
    }
    
    public void setControlSwitchId(ControlSwitchId controlSwitchId) {
        this.controlSwitchId = controlSwitchId;
    }
    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ControlSwitch) ) return false;
		 ControlSwitch castOther = ( ControlSwitch ) other; 
         
		 return ( (this.getControlSwitchId()==castOther.getControlSwitchId()) || ( this.getControlSwitchId()!=null && castOther.getControlSwitchId()!=null && this.getControlSwitchId().equals(castOther.getControlSwitchId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getControlSwitchId() == null ? 0 : this.getControlSwitchId().hashCode() );
         
         return result;
   }   


}


