package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * CountryTermUrl generated by hbm2java
 */
public class CountryTermUrl  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=3) private String countryCode;
     @Length(min=0, max=30) private String termUrlDescription;
     @Length(min=0, max=254) private String termUrl;

     // Constructors

    /** default constructor */
    public CountryTermUrl() {
    }

	/** minimal constructor */
    public CountryTermUrl(String countryCode) {
        this.countryCode = countryCode;
    }
    /** full constructor */
    public CountryTermUrl(String countryCode, String termUrlDescription, String termUrl) {
       this.countryCode = countryCode;
       this.termUrlDescription = termUrlDescription;
       this.termUrl = termUrl;
    }
   
    // Property accessors
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getTermUrlDescription() {
        return this.termUrlDescription;
    }
    
    public void setTermUrlDescription(String termUrlDescription) {
        this.termUrlDescription = termUrlDescription;
    }
    public String getTermUrl() {
        return this.termUrl;
    }
    
    public void setTermUrl(String termUrl) {
        this.termUrl = termUrl;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CountryTermUrl) ) return false;
		 CountryTermUrl castOther = ( CountryTermUrl ) other; 
         
		 return ( (this.getCountryCode()==castOther.getCountryCode()) || ( this.getCountryCode()!=null && castOther.getCountryCode()!=null && this.getCountryCode().equals(castOther.getCountryCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCountryCode() == null ? 0 : this.getCountryCode().hashCode() );
         
         
         return result;
   }   


}


