package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * CustVatRegistrationId generated by hbm2java
 */
public class CustVatRegistrationId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=15) private String custCode;
     @NotBlank @Length(min=0, max=3) private String countryCode;
     @NotBlank @Length(min=0, max=12) private String registrationId;

     // Constructors

    /** default constructor */
    public CustVatRegistrationId() {
    }

    /** full constructor */
    public CustVatRegistrationId(String custCode, String countryCode, String registrationId) {
       this.custCode = custCode;
       this.countryCode = countryCode;
       this.registrationId = registrationId;
    }
   
    // Property accessors
    public String getCustCode() {
        return this.custCode;
    }
    
    public void setCustCode(String custCode) {
        this.custCode = custCode;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getRegistrationId() {
        return this.registrationId;
    }
    
    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CustVatRegistrationId) ) return false;
		 CustVatRegistrationId castOther = ( CustVatRegistrationId ) other; 
         
		 return ( (this.getCustCode()==castOther.getCustCode()) || ( this.getCustCode()!=null && castOther.getCustCode()!=null && this.getCustCode().equals(castOther.getCustCode()) ) )
 && ( (this.getCountryCode()==castOther.getCountryCode()) || ( this.getCountryCode()!=null && castOther.getCountryCode()!=null && this.getCountryCode().equals(castOther.getCountryCode()) ) )
 && ( (this.getRegistrationId()==castOther.getRegistrationId()) || ( this.getRegistrationId()!=null && castOther.getRegistrationId()!=null && this.getRegistrationId().equals(castOther.getRegistrationId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCustCode() == null ? 0 : this.getCustCode().hashCode() );
         result = 37 * result + ( getCountryCode() == null ? 0 : this.getCountryCode().hashCode() );
         result = 37 * result + ( getRegistrationId() == null ? 0 : this.getRegistrationId().hashCode() );
         return result;
   }   


}


