package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=10) private String eventCode;
     @Length(min=0, max=30) private String eventName;
     @Length(min=0, max=200) private String eventInstruction;
     @Length(min=0, max=1) private String status;

     // Constructors

    /** default constructor */
    public Event() {
    }

	/** minimal constructor */
    public Event(String eventCode) {
        this.eventCode = eventCode;
    }
    /** full constructor */
    public Event(String eventCode, String eventName, String eventInstruction, String status) {
       this.eventCode = eventCode;
       this.eventName = eventName;
       this.eventInstruction = eventInstruction;
       this.status = status;
    }
   
    // Property accessors
    public String getEventCode() {
        return this.eventCode;
    }
    
    public void setEventCode(String eventCode) {
        this.eventCode = eventCode;
    }
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public String getEventInstruction() {
        return this.eventInstruction;
    }
    
    public void setEventInstruction(String eventInstruction) {
        this.eventInstruction = eventInstruction;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Event) ) return false;
		 Event castOther = ( Event ) other; 
         
		 return ( (this.getEventCode()==castOther.getEventCode()) || ( this.getEventCode()!=null && castOther.getEventCode()!=null && this.getEventCode().equals(castOther.getEventCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEventCode() == null ? 0 : this.getEventCode().hashCode() );
         
         
         
         return result;
   }   


}


