package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ExpressionGLCode generated by hbm2java
 */
public class ExpressionGLCode  implements java.io.Serializable {

    // Fields    

     private ExpressionGLCodeId expressionGLCodeId;
     @Length(min=0, max=45) private String GLCode;
     private Integer useProdFlag;
     @Length(min=0, max=45) private String noProdCode;
     @Length(min=0, max=45) private String interCompanyGLCode;

     // Constructors

    /** default constructor */
    public ExpressionGLCode() {
    }

	/** minimal constructor */
    public ExpressionGLCode(ExpressionGLCodeId expressionGLCodeId) {
        this.expressionGLCodeId = expressionGLCodeId;
    }
    /** full constructor */
    public ExpressionGLCode(ExpressionGLCodeId expressionGLCodeId, String GLCode, Integer useProdFlag, String noProdCode) {
       this.expressionGLCodeId = expressionGLCodeId;
       this.GLCode = GLCode;
       this.useProdFlag = useProdFlag;
       this.noProdCode = noProdCode;
    }
   
    // Property accessors
    public ExpressionGLCodeId getExpressionGLCodeId() {
        return this.expressionGLCodeId;
    }
    
    public void setExpressionGLCodeId(ExpressionGLCodeId expressionGLCodeId) {
        this.expressionGLCodeId = expressionGLCodeId;
    }
    public String getGLCode() {
        return this.GLCode;
    }
    
    public void setGLCode(String GLCode) {
        this.GLCode = GLCode;
    }
    public Integer getUseProdFlag() {
        return this.useProdFlag;
    }
    
    public void setUseProdFlag(Integer useProdFlag) {
        this.useProdFlag = useProdFlag;
    }
    public String getNoProdCode() {
        return this.noProdCode;
    }
    
    public void setNoProdCode(String noProdCode) {
        this.noProdCode = noProdCode;
    }

   public String getInterCompanyGLCode() {
        return interCompanyGLCode;
    }

    public void setInterCompanyGLCode(String interCompanyGLCode) {
        this.interCompanyGLCode = interCompanyGLCode;
    }

    public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExpressionGLCode) ) return false;
		 ExpressionGLCode castOther = ( ExpressionGLCode ) other; 
         
		 return ( (this.getExpressionGLCodeId()==castOther.getExpressionGLCodeId()) || ( this.getExpressionGLCodeId()!=null && castOther.getExpressionGLCodeId()!=null && this.getExpressionGLCodeId().equals(castOther.getExpressionGLCodeId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getExpressionGLCodeId() == null ? 0 : this.getExpressionGLCodeId().hashCode() );
         
         
         
         return result;
   }   


}


