package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * GLDepartment generated by hbm2java
 */
public class GLDepartment  implements java.io.Serializable {

    // Fields    

     private GLDepartmentId glDepartmentId;
     @Length(min=0, max=1) private String status;

     // Constructors

    /** default constructor */
    public GLDepartment() {
    }

	/** minimal constructor */
    public GLDepartment(GLDepartmentId glDepartmentId) {
        this.glDepartmentId = glDepartmentId;
    }
    /** full constructor */
    public GLDepartment(GLDepartmentId glDepartmentId, String status) {
       this.glDepartmentId = glDepartmentId;
       this.status = status;
    }
   
    // Property accessors
    public GLDepartmentId getGlDepartmentId() {
        return this.glDepartmentId;
    }
    
    public void setGlDepartmentId(GLDepartmentId glDepartmentId) {
        this.glDepartmentId = glDepartmentId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GLDepartment) ) return false;
		 GLDepartment castOther = ( GLDepartment ) other; 
         
		 return ( (this.getGlDepartmentId()==castOther.getGlDepartmentId()) || ( this.getGlDepartmentId()!=null && castOther.getGlDepartmentId()!=null && this.getGlDepartmentId().equals(castOther.getGlDepartmentId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGlDepartmentId() == null ? 0 : this.getGlDepartmentId().hashCode() );
         
         return result;
   }   


}


