package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * HighLevelService generated by hbm2java
 */
public class HighLevelService  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=45) private String highLevelServiceId;
     @NotBlank @Length(min=0, max=135) private String serviceDescription;
     private Boolean priceBookInd;

     // Constructors

    /** default constructor */
    public HighLevelService() {
    }

	/** minimal constructor */
    public HighLevelService(String highLevelServiceId, String serviceDescription) {
        this.highLevelServiceId = highLevelServiceId;
        this.serviceDescription = serviceDescription;
    }
    /** full constructor */
    public HighLevelService(String highLevelServiceId, String serviceDescription, Boolean priceBookInd) {
       this.highLevelServiceId = highLevelServiceId;
       this.serviceDescription = serviceDescription;
       this.priceBookInd = priceBookInd;
    }
   
    // Property accessors
    public String getHighLevelServiceId() {
        return this.highLevelServiceId;
    }
    
    public void setHighLevelServiceId(String highLevelServiceId) {
        this.highLevelServiceId = highLevelServiceId;
    }
    public String getServiceDescription() {
        return this.serviceDescription;
    }
    
    public void setServiceDescription(String serviceDescription) {
        this.serviceDescription = serviceDescription;
    }
    public Boolean getPriceBookInd() {
        return this.priceBookInd;
    }
    
    public void setPriceBookInd(Boolean priceBookInd) {
        this.priceBookInd = priceBookInd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HighLevelService) ) return false;
		 HighLevelService castOther = ( HighLevelService ) other; 
         
		 return ( (this.getHighLevelServiceId()==castOther.getHighLevelServiceId()) || ( this.getHighLevelServiceId()!=null && castOther.getHighLevelServiceId()!=null && this.getHighLevelServiceId().equals(castOther.getHighLevelServiceId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getHighLevelServiceId() == null ? 0 : this.getHighLevelServiceId().hashCode() );
         
         
         return result;
   }   


}


