package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * InspectionRateId generated by hbm2java
 */
public class InspectionRateId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=45) private String contractId;
     @NotBlank @Length(min=0, max=105) private String expressionId;
     @NotBlank @Length(min=0, max=105) private String location;
     @NotBlank @Length(min=0, max=45) private String groupId;
     @NotBlank @Length(min=0, max=45) private String vesselType;
     private Date beginDate;
     @NotBlank @Length(min=0, max=3) private String withInspection;
     @NotBlank @Length(min=0, max=12) private String serviceLevel;
     private Integer intData2;
     private Double floatData2;
     private Integer intData4;

     // Constructors

    /** default constructor */
    public InspectionRateId() {
    }

    /** full constructor */
    public InspectionRateId(String contractId, String expressionId, String location, String groupId, String vesselType, Date beginDate, String withInspection, String serviceLevel, Integer intData2, Double floatData2, Integer intData4) {
       this.contractId = contractId;
       this.expressionId = expressionId;
       this.location = location;
       this.groupId = groupId;
       this.vesselType = vesselType;
       this.beginDate = beginDate;
       this.withInspection = withInspection;
       this.serviceLevel = serviceLevel;
       this.intData2 = intData2;
       this.floatData2 = floatData2;
       this.intData4 = intData4;
    }
   
    // Property accessors
    public String getContractId() {
        return this.contractId;
    }
    
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }
    public String getExpressionId() {
        return this.expressionId;
    }
    
    public void setExpressionId(String expressionId) {
        this.expressionId = expressionId;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }
    public String getVesselType() {
        return this.vesselType;
    }
    
    public void setVesselType(String vesselType) {
        this.vesselType = vesselType;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
    public String getWithInspection() {
        return this.withInspection;
    }
    
    public void setWithInspection(String withInspection) {
        this.withInspection = withInspection;
    }
    public String getServiceLevel() {
        return this.serviceLevel;
    }
    
    public void setServiceLevel(String serviceLevel) {
        this.serviceLevel = serviceLevel;
    }
    public Integer getIntData2() {
        return this.intData2;
    }
    
    public void setIntData2(Integer intData2) {
        this.intData2 = intData2;
    }
    public Double getFloatData2() {
        return this.floatData2;
    }
    
    public void setFloatData2(Double floatData2) {
        this.floatData2 = floatData2;
    }
    public Integer getIntData4() {
        return this.intData4;
    }
    
    public void setIntData4(Integer intData4) {
        this.intData4 = intData4;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InspectionRateId) ) return false;
		 InspectionRateId castOther = ( InspectionRateId ) other; 
         
		 return ( (this.getContractId()==castOther.getContractId()) || ( this.getContractId()!=null && castOther.getContractId()!=null && this.getContractId().equals(castOther.getContractId()) ) )
 && ( (this.getExpressionId()==castOther.getExpressionId()) || ( this.getExpressionId()!=null && castOther.getExpressionId()!=null && this.getExpressionId().equals(castOther.getExpressionId()) ) )
 && ( (this.getLocation()==castOther.getLocation()) || ( this.getLocation()!=null && castOther.getLocation()!=null && this.getLocation().equals(castOther.getLocation()) ) )
 && ( (this.getGroupId()==castOther.getGroupId()) || ( this.getGroupId()!=null && castOther.getGroupId()!=null && this.getGroupId().equals(castOther.getGroupId()) ) )
 && ( (this.getVesselType()==castOther.getVesselType()) || ( this.getVesselType()!=null && castOther.getVesselType()!=null && this.getVesselType().equals(castOther.getVesselType()) ) )
 && ( (this.getBeginDate()==castOther.getBeginDate()) || ( this.getBeginDate()!=null && castOther.getBeginDate()!=null && this.getBeginDate().equals(castOther.getBeginDate()) ) )
 && ( (this.getWithInspection()==castOther.getWithInspection()) || ( this.getWithInspection()!=null && castOther.getWithInspection()!=null && this.getWithInspection().equals(castOther.getWithInspection()) ) )
 && ( (this.getServiceLevel()==castOther.getServiceLevel()) || ( this.getServiceLevel()!=null && castOther.getServiceLevel()!=null && this.getServiceLevel().equals(castOther.getServiceLevel()) ) )
 && ( (this.getIntData2()==castOther.getIntData2()) || ( this.getIntData2()!=null && castOther.getIntData2()!=null && this.getIntData2().equals(castOther.getIntData2()) ) )
 && ( (this.getFloatData2()==castOther.getFloatData2()) || ( this.getFloatData2()!=null && castOther.getFloatData2()!=null && this.getFloatData2().equals(castOther.getFloatData2()) ) )
 && ( (this.getIntData4()==castOther.getIntData4()) || ( this.getIntData4()!=null && castOther.getIntData4()!=null && this.getIntData4().equals(castOther.getIntData4()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getContractId() == null ? 0 : this.getContractId().hashCode() );
         result = 37 * result + ( getExpressionId() == null ? 0 : this.getExpressionId().hashCode() );
         result = 37 * result + ( getLocation() == null ? 0 : this.getLocation().hashCode() );
         result = 37 * result + ( getGroupId() == null ? 0 : this.getGroupId().hashCode() );
         result = 37 * result + ( getVesselType() == null ? 0 : this.getVesselType().hashCode() );
         result = 37 * result + ( getBeginDate() == null ? 0 : this.getBeginDate().hashCode() );
         result = 37 * result + ( getWithInspection() == null ? 0 : this.getWithInspection().hashCode() );
         result = 37 * result + ( getServiceLevel() == null ? 0 : this.getServiceLevel().hashCode() );
         result = 37 * result + ( getIntData2() == null ? 0 : this.getIntData2().hashCode() );
         result = 37 * result + ( getFloatData2() == null ? 0 : this.getFloatData2().hashCode() );
         result = 37 * result + ( getIntData4() == null ? 0 : this.getIntData4().hashCode() );
         return result;
   }   


}


