package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * JobContractProductService generated by hbm2java
 */
public class JobContractProductService  implements java.io.Serializable {

    // Fields    

     private long id;
     private JobContractProd jobContractProd;
     @NotBlank @Length(min=0, max=60) private String serviceName;
     @Length(min=0, max=45) private String serviceType;
     private Integer sortOrderNum;
     private Set<JobContractProductServiceControl> controls = new HashSet<JobContractProductServiceControl>(0);
     private Set<JobContractProductServiceResult> results = new HashSet<JobContractProductServiceResult>(0);

     // Constructors

    /** default constructor */
    public JobContractProductService() {
    }

	/** minimal constructor */
    public JobContractProductService(JobContractProd jobContractProd, String serviceName) {
        this.jobContractProd = jobContractProd;
        this.serviceName = serviceName;
    }
    /** full constructor */
    public JobContractProductService(JobContractProd jobContractProd, String serviceName, String serviceType, Integer sortOrderNum, Set<JobContractProductServiceControl> controls, Set<JobContractProductServiceResult> results) {
       this.jobContractProd = jobContractProd;
       this.serviceName = serviceName;
       this.serviceType = serviceType;
       this.sortOrderNum = sortOrderNum;
       this.controls = controls;
       this.results = results;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public JobContractProd getJobContractProd() {
        return this.jobContractProd;
    }
    
    public void setJobContractProd(JobContractProd jobContractProd) {
        this.jobContractProd = jobContractProd;
    }
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }
    public String getServiceType() {
        return this.serviceType;
    }
    
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }
    public Integer getSortOrderNum() {
        return this.sortOrderNum;
    }
    
    public void setSortOrderNum(Integer sortOrderNum) {
        this.sortOrderNum = sortOrderNum;
    }
    public Set<JobContractProductServiceControl> getControls() {
        return this.controls;
    }
    
    public void setControls(Set<JobContractProductServiceControl> controls) {
        this.controls = controls;
    }
    public Set<JobContractProductServiceResult> getResults() {
        return this.results;
    }
    
    public void setResults(Set<JobContractProductServiceResult> results) {
        this.results = results;
    }




}


