package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * JobContractManualTest generated by hbm2java
 */
public class JobContractManualTest  implements java.io.Serializable {

    // Fields    

     private long id;
     private JobContractProd jobContractProd;
     private Set<Prebill> prebills = new HashSet<Prebill>(0);
     private long jobManualTestId;
     @NotBlank @Length(min=0, max=96) private String testId;
     @Length(min=0, max=762) private String testDescription;
     private Double quantity;
     private Boolean ot;
     private Double unitPrice;
     @Length(min=0, max=254) private String lineDescription;
     @Length(min=0, max=45) private String contractRefNo;
     private Double discount;
     private Double totalPrice;
     private Integer sortOrderNum;

     // Constructors

    /** default constructor */
    public JobContractManualTest() {
    }

    /** full constructor */
    public JobContractManualTest(JobContractProd jobContractProd, Set<Prebill> prebills, long jobManualTestId, String testId, String testDescription, Double quantity, Boolean ot, Double unitPrice, String lineDescription, String contractRefNo, Double discount, Double totalPrice, Integer sortOrderNum) {
       this.jobContractProd = jobContractProd;
       this.prebills = prebills;
       this.jobManualTestId = jobManualTestId;
       this.testId = testId;
       this.testDescription = testDescription;
       this.quantity = quantity;
       this.ot = ot;
       this.unitPrice = unitPrice;
       this.lineDescription = lineDescription;
       this.contractRefNo = contractRefNo;
       this.discount = discount;
       this.totalPrice = totalPrice;
       this.sortOrderNum = sortOrderNum;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public JobContractProd getJobContractProd() {
        return this.jobContractProd;
    }
    
    public void setJobContractProd(JobContractProd jobContractProd) {
        this.jobContractProd = jobContractProd;
    }
    public Set<Prebill> getPrebills() {
        return this.prebills;
    }
    
    public void setPrebills(Set<Prebill> prebills) {
        this.prebills = prebills;
    }
    public long getJobManualTestId() {
        return this.jobManualTestId;
    }
    
    public void setJobManualTestId(long jobManualTestId) {
        this.jobManualTestId = jobManualTestId;
    }
    public String getTestId() {
        return this.testId;
    }
    
    public void setTestId(String testId) {
        this.testId = testId;
    }
    public String getTestDescription() {
        return this.testDescription;
    }
    
    public void setTestDescription(String testDescription) {
        this.testDescription = testDescription;
    }
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }
    public Boolean getOt() {
        return this.ot;
    }
    
    public void setOt(Boolean ot) {
        this.ot = ot;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public String getLineDescription() {
        return this.lineDescription;
    }
    
    public void setLineDescription(String lineDescription) {
        this.lineDescription = lineDescription;
    }
    public String getContractRefNo() {
        return this.contractRefNo;
    }
    
    public void setContractRefNo(String contractRefNo) {
        this.contractRefNo = contractRefNo;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Integer getSortOrderNum() {
        return this.sortOrderNum;
    }
    
    public void setSortOrderNum(Integer sortOrderNum) {
        this.sortOrderNum = sortOrderNum;
    }




}


