package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * JobContractService generated by hbm2java
 */
public class JobContractService  implements java.io.Serializable {

    // Fields    

     private long id;
     private JobContract jobContract;
     @NotBlank @Length(min=0, max=60) private String serviceName;
     @Length(min=0, max=45) private String serviceType;
     private Integer sortOrderNum;
     private Set<JobContractServiceControl> controls = new HashSet<JobContractServiceControl>(0);
     private Set<JobContractServiceResult> results = new HashSet<JobContractServiceResult>(0);

     // Constructors

    /** default constructor */
    public JobContractService() {
    }

	/** minimal constructor */
    public JobContractService(JobContract jobContract, String serviceName) {
        this.jobContract = jobContract;
        this.serviceName = serviceName;
    }
    /** full constructor */
    public JobContractService(JobContract jobContract, String serviceName, String serviceType, Integer sortOrderNum, Set<JobContractServiceControl> controls, Set<JobContractServiceResult> results) {
       this.jobContract = jobContract;
       this.serviceName = serviceName;
       this.serviceType = serviceType;
       this.sortOrderNum = sortOrderNum;
       this.controls = controls;
       this.results = results;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public JobContract getJobContract() {
        return this.jobContract;
    }
    
    public void setJobContract(JobContract jobContract) {
        this.jobContract = jobContract;
    }
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }
    public String getServiceType() {
        return this.serviceType;
    }
    
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }
    public Integer getSortOrderNum() {
        return this.sortOrderNum;
    }
    
    public void setSortOrderNum(Integer sortOrderNum) {
        this.sortOrderNum = sortOrderNum;
    }
    public Set<JobContractServiceControl> getControls() {
        return this.controls;
    }
    
    public void setControls(Set<JobContractServiceControl> controls) {
        this.controls = controls;
    }
    public Set<JobContractServiceResult> getResults() {
        return this.results;
    }
    
    public void setResults(Set<JobContractServiceResult> results) {
        this.results = results;
    }




}


