package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * JobContractVesselInspectionResult generated by hbm2java
 */
public class JobContractVesselInspectionResult  implements java.io.Serializable {

    // Fields    

     private long id;
     private JobContractVessel jobContractVessel;
     private Set<Prebill> prebills = new HashSet<Prebill>(0);
     @NotBlank @Length(min=0, max=105) private String expressionId;
     @NotBlank @Length(min=0, max=105) private String location;
     private Integer sortOrderNum;
     private Integer uomFlag;

     // Constructors

    /** default constructor */
    public JobContractVesselInspectionResult() {
    }

    /** full constructor */
    public JobContractVesselInspectionResult(JobContractVessel jobContractVessel, Set<Prebill> prebills, String expressionId, String location, Integer sortOrderNum, Integer uomFlag) {
       this.jobContractVessel = jobContractVessel;
       this.prebills = prebills;
       this.expressionId = expressionId;
       this.location = location;
       this.sortOrderNum = sortOrderNum;
       this.uomFlag = uomFlag;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public JobContractVessel getJobContractVessel() {
        return this.jobContractVessel;
    }
    
    public void setJobContractVessel(JobContractVessel jobContractVessel) {
        this.jobContractVessel = jobContractVessel;
    }
    public Set<Prebill> getPrebills() {
        return this.prebills;
    }
    
    public void setPrebills(Set<Prebill> prebills) {
        this.prebills = prebills;
    }
    public String getExpressionId() {
        return this.expressionId;
    }
    
    public void setExpressionId(String expressionId) {
        this.expressionId = expressionId;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Integer getSortOrderNum() {
        return this.sortOrderNum;
    }
    
    public void setSortOrderNum(Integer sortOrderNum) {
        this.sortOrderNum = sortOrderNum;
    }
    public Integer getUomFlag() {
        return this.uomFlag;
    }
    
    public void setUomFlag(Integer uomFlag) {
        this.uomFlag = uomFlag;
    }




}


