package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * JobContractAttach generated by hbm2java
 */
public class JobContractAttach  implements java.io.Serializable {

    // Fields    

     private long id;
     @NotBlank @Length(min=0, max=128) private String fileName;
     @NotBlank @Length(min=0, max=128) private String systemFileName;
     @NotBlank @Length(min=0, max=128) private String jobNumber;
     @Length(min=0, max=128) private String description;
     private JobContractAttachType jobContractAttachType;
     @Length(min=0, max=12) private String type;
     private JobOrder jobOrder;
     @NotBlank @Length(min=0, max=15) private String contractCode;
     private long jobContractId;
     private Contract contract;
     private JobContract jobContract;

     // Constructors

    /** default constructor */
    public JobContractAttach() {
    }

	/** minimal constructor */
    public JobContractAttach(String fileName, String systemFileName, String jobNumber, String type, String contractCode) {
        this.fileName = fileName;
        this.systemFileName = systemFileName;
        this.jobNumber = jobNumber;
        this.type = type;
        this.contractCode = contractCode;
    }
    /** full constructor */
    public JobContractAttach(String fileName, String systemFileName, String jobNumber, String description, JobContractAttachType jobContractAttachType, String type, JobOrder jobOrder, String contractCode, long jobContractId, Contract contract, JobContract jobContract) {
       this.fileName = fileName;
       this.systemFileName = systemFileName;
       this.jobNumber = jobNumber;
       this.description = description;
       this.jobContractAttachType = jobContractAttachType;
       this.type = type;
       this.jobOrder = jobOrder;
       this.contractCode = contractCode;
       this.jobContractId = jobContractId;
       this.contract = contract;
       this.jobContract = jobContract;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getSystemFileName() {
        return this.systemFileName;
    }
    
    public void setSystemFileName(String systemFileName) {
        this.systemFileName = systemFileName;
    }
    public String getJobNumber() {
        return this.jobNumber;
    }
    
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public JobContractAttachType getJobContractAttachType() {
        return this.jobContractAttachType;
    }
    
    public void setJobContractAttachType(JobContractAttachType jobContractAttachType) {
        this.jobContractAttachType = jobContractAttachType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public JobOrder getJobOrder() {
        return this.jobOrder;
    }
    
    public void setJobOrder(JobOrder jobOrder) {
        this.jobOrder = jobOrder;
    }
    public String getContractCode() {
        return this.contractCode;
    }
    
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode;
    }
    public long getJobContractId() {
        return this.jobContractId;
    }
    
    public void setJobContractId(long jobContractId) {
        this.jobContractId = jobContractId;
    }
    public Contract getContract() {
        return this.contract;
    }
    
    public void setContract(Contract contract) {
        this.contract = contract;
    }
    public JobContract getJobContract() {
        return this.jobContract;
    }
    
    public void setJobContract(JobContract jobContract) {
        this.jobContract = jobContract;
    }




}


