package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * JobNote generated by hbm2java
 */
public class JobNote  implements java.io.Serializable {

    // Fields    

     private long id;
     @NotBlank @Length(min=0, max=128) private String noteSummary;
     @Length(min=0, max=1024) private String note;
     @NotBlank @Length(min=0, max=128) private String jobNumber;
     private JobOrder jobOrder;

     // Constructors

    /** default constructor */
    public JobNote() {
    }

	/** minimal constructor */
    public JobNote(String noteSummary, String jobNumber) {
        this.noteSummary = noteSummary;
        this.jobNumber = jobNumber;
    }
    /** full constructor */
    public JobNote(String noteSummary, String note, String jobNumber, JobOrder jobOrder) {
       this.noteSummary = noteSummary;
       this.note = note;
       this.jobNumber = jobNumber;
       this.jobOrder = jobOrder;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNoteSummary() {
        return this.noteSummary;
    }
    
    public void setNoteSummary(String noteSummary) {
        this.noteSummary = noteSummary;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getJobNumber() {
        return this.jobNumber;
    }
    
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }
    public JobOrder getJobOrder() {
        return this.jobOrder;
    }
    
    public void setJobOrder(JobOrder jobOrder) {
        this.jobOrder = jobOrder;
    }




}


