package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * JobProdQty generated by hbm2java
 */
public class JobProdQty  implements java.io.Serializable {

    // Fields    

     private long id;
     @NotBlank @Length(min=0, max=40) private String group;
     @Length(min=0, max=4) private String option;
     @Length(min=0, max=4) private String plusMinus;
     private int plusMinusPct;
     private double productQty;
     @NotBlank @Length(min=0, max=4) private String uom;
     @Length(min=0, max=64) private String drafts;
     @Length(min=0, max=256) private String tanks;
     private Integer prodSeqNum;
     private Integer linkedVslRow;
     @Length(min=0, max=128) private String jobNumber;
     private JobProd jobProd;

     // Constructors

    /** default constructor */
    public JobProdQty() {
    }

	/** minimal constructor */
    public JobProdQty(String group, String uom) {
        this.group = group;
        this.uom = uom;
    }
    /** full constructor */
    public JobProdQty(String group, String option, String plusMinus, int plusMinusPct, double productQty, String uom, String drafts, String tanks, Integer prodSeqNum, Integer linkedVslRow, String jobNumber, JobProd jobProd) {
       this.group = group;
       this.option = option;
       this.plusMinus = plusMinus;
       this.plusMinusPct = plusMinusPct;
       this.productQty = productQty;
       this.uom = uom;
       this.drafts = drafts;
       this.tanks = tanks;
       this.prodSeqNum = prodSeqNum;
       this.linkedVslRow = linkedVslRow;
       this.jobNumber = jobNumber;
       this.jobProd = jobProd;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getGroup() {
        return this.group;
    }
    
    public void setGroup(String group) {
        this.group = group;
    }
    public String getOption() {
        return this.option;
    }
    
    public void setOption(String option) {
        this.option = option;
    }
    public String getPlusMinus() {
        return this.plusMinus;
    }
    
    public void setPlusMinus(String plusMinus) {
        this.plusMinus = plusMinus;
    }
    public int getPlusMinusPct() {
        return this.plusMinusPct;
    }
    
    public void setPlusMinusPct(int plusMinusPct) {
        this.plusMinusPct = plusMinusPct;
    }
    public double getProductQty() {
        return this.productQty;
    }
    
    public void setProductQty(double productQty) {
        this.productQty = productQty;
    }
    public String getUom() {
        return this.uom;
    }
    
    public void setUom(String uom) {
        this.uom = uom;
    }
    public String getDrafts() {
        return this.drafts;
    }
    
    public void setDrafts(String drafts) {
        this.drafts = drafts;
    }
    public String getTanks() {
        return this.tanks;
    }
    
    public void setTanks(String tanks) {
        this.tanks = tanks;
    }
    public Integer getProdSeqNum() {
        return this.prodSeqNum;
    }
    
    public void setProdSeqNum(Integer prodSeqNum) {
        this.prodSeqNum = prodSeqNum;
    }
    public Integer getLinkedVslRow() {
        return this.linkedVslRow;
    }
    
    public void setLinkedVslRow(Integer linkedVslRow) {
        this.linkedVslRow = linkedVslRow;
    }
    public String getJobNumber() {
        return this.jobNumber;
    }
    
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }
    public JobProd getJobProd() {
        return this.jobProd;
    }
    
    public void setJobProd(JobProd jobProd) {
        this.jobProd = jobProd;
    }




}


