package com.intertek.entity;
// Generated Nov 18, 2007 11:53:00 AM by Hibernate Tools 3.2.0.beta6a


import 
    org.springmodules.validation.bean.conf.loader.annotation.handler.*
  ;

/**
 * JobProdContract generated by hbm2java
 */
public class JobProdContract  implements java.io.Serializable {

    // Fields    

     private long id;
     @NotBlank @Length(min=0, max=16) private String group;
     @Length(min=0, max=4) private String option;
     @Length(min=0, max=4) private String plusMinus;
     private int plusMinusPct;
     private double productQty;
     @NotBlank @Length(min=0, max=4) private String uom;
     @Length(min=0, max=256) private String jobVesselName;
     @Length(min=0, max=128) private String jobNumber;
     private JobVessel jobVessel;

     // Constructors

    /** default constructor */
    public JobProdContract() {
    }

	/** minimal constructor */
    public JobProdContract(String group, String uom) {
        this.group = group;
        this.uom = uom;
    }
    /** full constructor */
    public JobProdContract(String group, String option, String plusMinus, int plusMinusPct, double productQty, String uom, String jobVesselName, String jobNumber, JobVessel jobVessel) {
       this.group = group;
       this.option = option;
       this.plusMinus = plusMinus;
       this.plusMinusPct = plusMinusPct;
       this.productQty = productQty;
       this.uom = uom;
       this.jobVesselName = jobVesselName;
       this.jobNumber = jobNumber;
       this.jobVessel = jobVessel;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getGroup() {
        return this.group;
    }
    
    public void setGroup(String group) {
        this.group = group;
    }
    public String getOption() {
        return this.option;
    }
    
    public void setOption(String option) {
        this.option = option;
    }
    public String getPlusMinus() {
        return this.plusMinus;
    }
    
    public void setPlusMinus(String plusMinus) {
        this.plusMinus = plusMinus;
    }
    public int getPlusMinusPct() {
        return this.plusMinusPct;
    }
    
    public void setPlusMinusPct(int plusMinusPct) {
        this.plusMinusPct = plusMinusPct;
    }
    public double getProductQty() {
        return this.productQty;
    }
    
    public void setProductQty(double productQty) {
        this.productQty = productQty;
    }
    public String getUom() {
        return this.uom;
    }
    
    public void setUom(String uom) {
        this.uom = uom;
    }
    public String getJobVesselName() {
        return this.jobVesselName;
    }
    
    public void setJobVesselName(String jobVesselName) {
        this.jobVesselName = jobVesselName;
    }
    public String getJobNumber() {
        return this.jobNumber;
    }
    
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }
    public JobVessel getJobVessel() {
        return this.jobVessel;
    }
    
    public void setJobVessel(JobVessel jobVessel) {
        this.jobVessel = jobVessel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JobProdContract) ) return false;
		 JobProdContract castOther = ( JobProdContract ) other; 
         
		 return ( (this.getGroup()==castOther.getGroup()) || ( this.getGroup()!=null && castOther.getGroup()!=null && this.getGroup().equals(castOther.getGroup()) ) )
 && ( (this.getOption()==castOther.getOption()) || ( this.getOption()!=null && castOther.getOption()!=null && this.getOption().equals(castOther.getOption()) ) )
 && ( (this.getPlusMinus()==castOther.getPlusMinus()) || ( this.getPlusMinus()!=null && castOther.getPlusMinus()!=null && this.getPlusMinus().equals(castOther.getPlusMinus()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         
         result = 37 * result + ( getGroup() == null ? 0 : this.getGroup().hashCode() );
         result = 37 * result + ( getOption() == null ? 0 : this.getOption().hashCode() );
         result = 37 * result + ( getPlusMinus() == null ? 0 : this.getPlusMinus().hashCode() );
         
         
         
         
         
         
         return result;
   }   


}


