package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * LabCapabilityId generated by hbm2java
 */
public class LabCapabilityId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=96) private String testId;
     @NotBlank @Length(min=0, max=30) private String location;

     // Constructors

    /** default constructor */
    public LabCapabilityId() {
    }

    /** full constructor */
    public LabCapabilityId(String testId, String location) {
       this.testId = testId;
       this.location = location;
    }
   
    // Property accessors
    public String getTestId() {
        return this.testId;
    }
    
    public void setTestId(String testId) {
        this.testId = testId;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LabCapabilityId) ) return false;
		 LabCapabilityId castOther = ( LabCapabilityId ) other; 
         
		 return ( (this.getTestId()==castOther.getTestId()) || ( this.getTestId()!=null && castOther.getTestId()!=null && this.getTestId().equals(castOther.getTestId()) ) )
 && ( (this.getLocation()==castOther.getLocation()) || ( this.getLocation()!=null && castOther.getLocation()!=null && this.getLocation().equals(castOther.getLocation()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTestId() == null ? 0 : this.getTestId().hashCode() );
         result = 37 * result + ( getLocation() == null ? 0 : this.getLocation().hashCode() );
         return result;
   }   


}


