package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * Notes generated by hbm2java
 */
public class Notes  implements java.io.Serializable {

    // Fields    

     private long id;
     @Length(min=0, max=1024) private String noteDetails;
     @Length(min=0, max=128) private String noteSummary;
     private Date dateTimeAdded;
     @Length(min=0, max=128) private String addedByUserName;
     private String noteCode;
     @Length(min=0, max=128) private String noteType;
     private User addedBy;

     // Constructors

    /** default constructor */
    public Notes() {
    }

    /** full constructor */
    public Notes(String noteDetails, String noteSummary, Date dateTimeAdded, String addedByUserName, String noteCode, String noteType, User addedBy) {
       this.noteDetails = noteDetails;
       this.noteSummary = noteSummary;
       this.dateTimeAdded = dateTimeAdded;
       this.addedByUserName = addedByUserName;
       this.noteCode = noteCode;
       this.noteType = noteType;
       this.addedBy = addedBy;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNoteDetails() {
        return this.noteDetails;
    }
    
    public void setNoteDetails(String noteDetails) {
        this.noteDetails = noteDetails;
    }
    public String getNoteSummary() {
        return this.noteSummary;
    }
    
    public void setNoteSummary(String noteSummary) {
        this.noteSummary = noteSummary;
    }
    public Date getDateTimeAdded() {
        return this.dateTimeAdded;
    }
    
    public void setDateTimeAdded(Date dateTimeAdded) {
        this.dateTimeAdded = dateTimeAdded;
    }
    public String getAddedByUserName() {
        return this.addedByUserName;
    }
    
    public void setAddedByUserName(String addedByUserName) {
        this.addedByUserName = addedByUserName;
    }
    public String getNoteCode() {
        return this.noteCode;
    }
    
    public void setNoteCode(String noteCode) {
        this.noteCode = noteCode;
    }
    public String getNoteType() {
        return this.noteType;
    }
    
    public void setNoteType(String noteType) {
        this.noteType = noteType;
    }
    public User getAddedBy() {
        return this.addedBy;
    }
    
    public void setAddedBy(User addedBy) {
        this.addedBy = addedBy;
    }




}


