package com.intertek.entity;

// Generated by Hibernate Tools 3.2.0.beta8

import java.util.Date;

import org.springmodules.validation.bean.conf.loader.annotation.handler.Length;

import com.intertek.phoenix.entity.Collectable;

/**
 * ProductGroup generated by hbm2java
 */
public class ProductGroup implements java.io.Serializable, Collectable {

    // Fields

    private ProductGroupId productGroupId;
    @Length(min = 0, max = 450)
    private String rbKey;
    @Length(min = 0, max = 45)
    private String productGroupMaster;
    private Date endDate;
    @Length(min = 0, max = 450)
    private String rbValue;
    private Integer uomFlag;
    private Integer additionalVesselPriceFlag;

    @Length(min = 0, max = 8)
    private String newFlag;
    @Length(min = 0, max = 8)
    private String updateFlag;
    
    // Constructors

    /** default constructor */
    public ProductGroup() {
    }

    /** minimal constructor */
    public ProductGroup(ProductGroupId productGroupId) {
        this.productGroupId = productGroupId;
    }

    /** full constructor */
    public ProductGroup(ProductGroupId productGroupId, String rbKey, String productGroupMaster, Date endDate, String rbValue, Integer uomFlag,
            Integer additionalVesselPriceFlag) {
        this.productGroupId = productGroupId;
        this.rbKey = rbKey;
        this.productGroupMaster = productGroupMaster;
        this.endDate = endDate;
        this.rbValue = rbValue;
        this.uomFlag = uomFlag;
        this.additionalVesselPriceFlag = additionalVesselPriceFlag;
    }

    // Property accessors
    public ProductGroupId getProductGroupId() {
        return this.productGroupId;
    }

    public void setProductGroupId(ProductGroupId productGroupId) {
        this.productGroupId = productGroupId;
    }

    public String getRbKey() {
        return this.rbKey;
    }

    public void setRbKey(String rbKey) {
        this.rbKey = rbKey;
    }

    public String getProductGroupMaster() {
        return this.productGroupMaster;
    }

    public void setProductGroupMaster(String productGroupMaster) {
        this.productGroupMaster = productGroupMaster;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getRbValue() {
        return this.rbValue;
    }

    public void setRbValue(String rbValue) {
        this.rbValue = rbValue;
    }

    public Integer getUomFlag() {
        return this.uomFlag;
    }

    public void setUomFlag(Integer uomFlag) {
        this.uomFlag = uomFlag;
    }

    public Integer getAdditionalVesselPriceFlag() {
        return this.additionalVesselPriceFlag;
    }

    public void setAdditionalVesselPriceFlag(Integer additionalVesselPriceFlag) {
        this.additionalVesselPriceFlag = additionalVesselPriceFlag;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ProductGroup))
            return false;
        ProductGroup castOther = (ProductGroup) other;

        return ((this.getProductGroupId() == castOther.getProductGroupId()) || (this.getProductGroupId() != null && castOther.getProductGroupId() != null && this
                .getProductGroupId().equals(castOther.getProductGroupId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getProductGroupId() == null ? 0 : this.getProductGroupId().hashCode());

        return result;
    }

    @Override
    public String getNewFlag() {
        return newFlag;
    }

    @Override
    public String getUpdateFlag() {
        return updateFlag;
    }

    public void setNewFlag(String newFlag) {
        this.newFlag = newFlag;
    }

    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag;
    }

}
