package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ReferenceField generated by hbm2java
 */
public class ReferenceField  implements java.io.Serializable {

    // Fields    

     private ReferenceFieldId referenceFieldId;
     private Integer sortOrderNum;

     // Constructors

    /** default constructor */
    public ReferenceField() {
    }

	/** minimal constructor */
    public ReferenceField(ReferenceFieldId referenceFieldId) {
        this.referenceFieldId = referenceFieldId;
    }
    /** full constructor */
    public ReferenceField(ReferenceFieldId referenceFieldId, Integer sortOrderNum) {
       this.referenceFieldId = referenceFieldId;
       this.sortOrderNum = sortOrderNum;
    }
   
    // Property accessors
    public ReferenceFieldId getReferenceFieldId() {
        return this.referenceFieldId;
    }
    
    public void setReferenceFieldId(ReferenceFieldId referenceFieldId) {
        this.referenceFieldId = referenceFieldId;
    }
    public Integer getSortOrderNum() {
        return this.sortOrderNum;
    }
    
    public void setSortOrderNum(Integer sortOrderNum) {
        this.sortOrderNum = sortOrderNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReferenceField) ) return false;
		 ReferenceField castOther = ( ReferenceField ) other; 
         
		 return ( (this.getReferenceFieldId()==castOther.getReferenceFieldId()) || ( this.getReferenceFieldId()!=null && castOther.getReferenceFieldId()!=null && this.getReferenceFieldId().equals(castOther.getReferenceFieldId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getReferenceFieldId() == null ? 0 : this.getReferenceFieldId().hashCode() );
         
         return result;
   }   


}


