package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * RevisionNoteId generated by hbm2java
 */
public class RevisionNoteId  implements java.io.Serializable {

    // Fields    

     private long revisionNumber;
     @NotBlank @Length(min=0, max=128) private String jobNumber;

     // Constructors

    /** default constructor */
    public RevisionNoteId() {
    }

    /** full constructor */
    public RevisionNoteId(long revisionNumber, String jobNumber) {
       this.revisionNumber = revisionNumber;
       this.jobNumber = jobNumber;
    }
   
    // Property accessors
    public long getRevisionNumber() {
        return this.revisionNumber;
    }
    
    public void setRevisionNumber(long revisionNumber) {
        this.revisionNumber = revisionNumber;
    }
    public String getJobNumber() {
        return this.jobNumber;
    }
    
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RevisionNoteId) ) return false;
		 RevisionNoteId castOther = ( RevisionNoteId ) other; 
         
		 return (this.getRevisionNumber()==castOther.getRevisionNumber())
 && ( (this.getJobNumber()==castOther.getJobNumber()) || ( this.getJobNumber()!=null && castOther.getJobNumber()!=null && this.getJobNumber().equals(castOther.getJobNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getRevisionNumber();
         result = 37 * result + ( getJobNumber() == null ? 0 : this.getJobNumber().hashCode() );
         return result;
   }   


}


