package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ServiceVersion generated by hbm2java
 */
public class ServiceVersion  implements java.io.Serializable {

    // Fields    

     private ServiceVersionId serviceVersionId;
     private Date endDate;
     @Length(min=0, max=3) private String levelToggle;

     // Constructors

    /** default constructor */
    public ServiceVersion() {
    }

	/** minimal constructor */
    public ServiceVersion(ServiceVersionId serviceVersionId) {
        this.serviceVersionId = serviceVersionId;
    }
    /** full constructor */
    public ServiceVersion(ServiceVersionId serviceVersionId, Date endDate, String levelToggle) {
       this.serviceVersionId = serviceVersionId;
       this.endDate = endDate;
       this.levelToggle = levelToggle;
    }
   
    // Property accessors
    public ServiceVersionId getServiceVersionId() {
        return this.serviceVersionId;
    }
    
    public void setServiceVersionId(ServiceVersionId serviceVersionId) {
        this.serviceVersionId = serviceVersionId;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getLevelToggle() {
        return this.levelToggle;
    }
    
    public void setLevelToggle(String levelToggle) {
        this.levelToggle = levelToggle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ServiceVersion) ) return false;
		 ServiceVersion castOther = ( ServiceVersion ) other; 
         
		 return ( (this.getServiceVersionId()==castOther.getServiceVersionId()) || ( this.getServiceVersionId()!=null && castOther.getServiceVersionId()!=null && this.getServiceVersionId().equals(castOther.getServiceVersionId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getServiceVersionId() == null ? 0 : this.getServiceVersionId().hashCode() );
         
         
         return result;
   }   


}


