package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * SlatePriceBookId generated by hbm2java
 */
public class SlatePriceBookId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=45) private String slateId;
     @NotBlank @Length(min=0, max=45) private String priceBookId;
     private Date beginDate;

     // Constructors

    /** default constructor */
    public SlatePriceBookId() {
    }

    /** full constructor */
    public SlatePriceBookId(String slateId, String priceBookId, Date beginDate) {
       this.slateId = slateId;
       this.priceBookId = priceBookId;
       this.beginDate = beginDate;
    }
   
    // Property accessors
    public String getSlateId() {
        return this.slateId;
    }
    
    public void setSlateId(String slateId) {
        this.slateId = slateId;
    }
    public String getPriceBookId() {
        return this.priceBookId;
    }
    
    public void setPriceBookId(String priceBookId) {
        this.priceBookId = priceBookId;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SlatePriceBookId) ) return false;
		 SlatePriceBookId castOther = ( SlatePriceBookId ) other; 
         
		 return ( (this.getSlateId()==castOther.getSlateId()) || ( this.getSlateId()!=null && castOther.getSlateId()!=null && this.getSlateId().equals(castOther.getSlateId()) ) )
 && ( (this.getPriceBookId()==castOther.getPriceBookId()) || ( this.getPriceBookId()!=null && castOther.getPriceBookId()!=null && this.getPriceBookId().equals(castOther.getPriceBookId()) ) )
 && ( (this.getBeginDate()==castOther.getBeginDate()) || ( this.getBeginDate()!=null && castOther.getBeginDate()!=null && this.getBeginDate().equals(castOther.getBeginDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSlateId() == null ? 0 : this.getSlateId().hashCode() );
         result = 37 * result + ( getPriceBookId() == null ? 0 : this.getPriceBookId().hashCode() );
         result = 37 * result + ( getBeginDate() == null ? 0 : this.getBeginDate().hashCode() );
         return result;
   }   


}


