package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * SlatePrice generated by hbm2java
 */
public class SlatePrice  implements java.io.Serializable {

    // Fields    

     private SlatePriceId slatePriceId;
     private Integer seqNum;
     @Length(min=0, max=9) private String currencyCD;
     private Double unitPrice;
     @Length(min=0, max=45) private String contractRef;
     private Date endDate;
     private Slate slate;

     // Constructors

    /** default constructor */
    public SlatePrice() {
    }

	/** minimal constructor */
    public SlatePrice(SlatePriceId slatePriceId) {
        this.slatePriceId = slatePriceId;
    }
    /** full constructor */
    public SlatePrice(SlatePriceId slatePriceId, Integer seqNum, String currencyCD, Double unitPrice, String contractRef, Date endDate, Slate slate) {
       this.slatePriceId = slatePriceId;
       this.seqNum = seqNum;
       this.currencyCD = currencyCD;
       this.unitPrice = unitPrice;
       this.contractRef = contractRef;
       this.endDate = endDate;
       this.slate = slate;
    }
   
    // Property accessors
    public SlatePriceId getSlatePriceId() {
        return this.slatePriceId;
    }
    
    public void setSlatePriceId(SlatePriceId slatePriceId) {
        this.slatePriceId = slatePriceId;
    }
    public Integer getSeqNum() {
        return this.seqNum;
    }
    
    public void setSeqNum(Integer seqNum) {
        this.seqNum = seqNum;
    }
    public String getCurrencyCD() {
        return this.currencyCD;
    }
    
    public void setCurrencyCD(String currencyCD) {
        this.currencyCD = currencyCD;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public String getContractRef() {
        return this.contractRef;
    }
    
    public void setContractRef(String contractRef) {
        this.contractRef = contractRef;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Slate getSlate() {
        return this.slate;
    }
    
    public void setSlate(Slate slate) {
        this.slate = slate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SlatePrice) ) return false;
		 SlatePrice castOther = ( SlatePrice ) other; 
         
		 return ( (this.getSlatePriceId()==castOther.getSlatePriceId()) || ( this.getSlatePriceId()!=null && castOther.getSlatePriceId()!=null && this.getSlatePriceId().equals(castOther.getSlatePriceId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSlatePriceId() == null ? 0 : this.getSlatePriceId().hashCode() );
         
         
         
         
         
         
         return result;
   }   


}


