package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * SlatePriceBook generated by hbm2java
 */
public class SlatePriceBook  implements java.io.Serializable {

    // Fields    

     private SlatePriceBookId slatePriceBookId;
     private Date endDate;

     // Constructors

    /** default constructor */
    public SlatePriceBook() {
    }

	/** minimal constructor */
    public SlatePriceBook(SlatePriceBookId slatePriceBookId) {
        this.slatePriceBookId = slatePriceBookId;
    }
    /** full constructor */
    public SlatePriceBook(SlatePriceBookId slatePriceBookId, Date endDate) {
       this.slatePriceBookId = slatePriceBookId;
       this.endDate = endDate;
    }
   
    // Property accessors
    public SlatePriceBookId getSlatePriceBookId() {
        return this.slatePriceBookId;
    }
    
    public void setSlatePriceBookId(SlatePriceBookId slatePriceBookId) {
        this.slatePriceBookId = slatePriceBookId;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SlatePriceBook) ) return false;
		 SlatePriceBook castOther = ( SlatePriceBook ) other; 
         
		 return ( (this.getSlatePriceBookId()==castOther.getSlatePriceBookId()) || ( this.getSlatePriceBookId()!=null && castOther.getSlatePriceBookId()!=null && this.getSlatePriceBookId().equals(castOther.getSlatePriceBookId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSlatePriceBookId() == null ? 0 : this.getSlatePriceBookId().hashCode() );
         
         return result;
   }   


}


