package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * TaxCodeTaxRate generated by hbm2java
 */
public class TaxCodeTaxRate  implements java.io.Serializable {

    // Fields    

     private TaxCodeTaxRateId taxCodeTaxRateId;
     private TaxCode taxCodeHeader;

     // Constructors

    /** default constructor */
    public TaxCodeTaxRate() {
    }

	/** minimal constructor */
    public TaxCodeTaxRate(TaxCodeTaxRateId taxCodeTaxRateId) {
        this.taxCodeTaxRateId = taxCodeTaxRateId;
    }
    /** full constructor */
    public TaxCodeTaxRate(TaxCodeTaxRateId taxCodeTaxRateId, TaxCode taxCodeHeader) {
       this.taxCodeTaxRateId = taxCodeTaxRateId;
       this.taxCodeHeader = taxCodeHeader;
    }
   
    // Property accessors
    public TaxCodeTaxRateId getTaxCodeTaxRateId() {
        return this.taxCodeTaxRateId;
    }
    
    public void setTaxCodeTaxRateId(TaxCodeTaxRateId taxCodeTaxRateId) {
        this.taxCodeTaxRateId = taxCodeTaxRateId;
    }
    public TaxCode getTaxCodeHeader() {
        return this.taxCodeHeader;
    }
    
    public void setTaxCodeHeader(TaxCode taxCodeHeader) {
        this.taxCodeHeader = taxCodeHeader;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaxCodeTaxRate) ) return false;
		 TaxCodeTaxRate castOther = ( TaxCodeTaxRate ) other; 
         
		 return ( (this.getTaxCodeTaxRateId()==castOther.getTaxCodeTaxRateId()) || ( this.getTaxCodeTaxRateId()!=null && castOther.getTaxCodeTaxRateId()!=null && this.getTaxCodeTaxRateId().equals(castOther.getTaxCodeTaxRateId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTaxCodeTaxRateId() == null ? 0 : this.getTaxCodeTaxRateId().hashCode() );
         
         return result;
   }   


}


