package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * TestProduct generated by hbm2java
 */
public class TestProduct  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=45) private String testProductId;
     @Length(min=0, max=762) private String testProductDescription;

     // Constructors

    /** default constructor */
    public TestProduct() {
    }

	/** minimal constructor */
    public TestProduct(String testProductId) {
        this.testProductId = testProductId;
    }
    /** full constructor */
    public TestProduct(String testProductId, String testProductDescription) {
       this.testProductId = testProductId;
       this.testProductDescription = testProductDescription;
    }
   
    // Property accessors
    public String getTestProductId() {
        return this.testProductId;
    }
    
    public void setTestProductId(String testProductId) {
        this.testProductId = testProductId;
    }
    public String getTestProductDescription() {
        return this.testProductDescription;
    }
    
    public void setTestProductDescription(String testProductDescription) {
        this.testProductDescription = testProductDescription;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TestProduct) ) return false;
		 TestProduct castOther = ( TestProduct ) other; 
         
		 return ( (this.getTestProductId()==castOther.getTestProductId()) || ( this.getTestProductId()!=null && castOther.getTestProductId()!=null && this.getTestProductId().equals(castOther.getTestProductId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTestProductId() == null ? 0 : this.getTestProductId().hashCode() );
         
         return result;
   }   


}


