package com.intertek.entity;

// Generated by Hibernate Tools 3.2.0.beta8

import java.util.Date;

import org.springmodules.validation.bean.conf.loader.annotation.handler.Length;

import com.intertek.phoenix.entity.Collectable;

/**
 * TestPrice generated by hbm2java
 */
public class TestPrice implements java.io.Serializable, Collectable {

    // Fields

    private TestPriceId testPriceId;
    private Integer seqNum;
    @Length(min = 0, max = 9)
    private String currencyCD;
    private Double unitPrice;
    @Length(min = 0, max = 45)
    private String contractRef;
    private Date endDate;
    private Test test;

    @Length(min = 0, max = 8)
    private String newFlag;
    @Length(min = 0, max = 8)
    private String updateFlag;

    // Constructors

    /** default constructor */
    public TestPrice() {
    }

    /** minimal constructor */
    public TestPrice(TestPriceId testPriceId) {
        this.testPriceId = testPriceId;
    }

    /** full constructor */
    public TestPrice(TestPriceId testPriceId, Integer seqNum, String currencyCD, Double unitPrice, String contractRef, Date endDate, Test test) {
        this.testPriceId = testPriceId;
        this.seqNum = seqNum;
        this.currencyCD = currencyCD;
        this.unitPrice = unitPrice;
        this.contractRef = contractRef;
        this.endDate = endDate;
        this.test = test;
    }

    // Property accessors
    public TestPriceId getTestPriceId() {
        return this.testPriceId;
    }

    public void setTestPriceId(TestPriceId testPriceId) {
        this.testPriceId = testPriceId;
    }

    public Integer getSeqNum() {
        return this.seqNum;
    }

    public void setSeqNum(Integer seqNum) {
        this.seqNum = seqNum;
    }

    public String getCurrencyCD() {
        return this.currencyCD;
    }

    public void setCurrencyCD(String currencyCD) {
        this.currencyCD = currencyCD;
    }

    public Double getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public String getContractRef() {
        return this.contractRef;
    }

    public void setContractRef(String contractRef) {
        this.contractRef = contractRef;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Test getTest() {
        return this.test;
    }

    public void setTest(Test test) {
        this.test = test;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof TestPrice))
            return false;
        TestPrice castOther = (TestPrice) other;

        return ((this.getTestPriceId() == castOther.getTestPriceId()) || (this.getTestPriceId() != null && castOther.getTestPriceId() != null && this
                .getTestPriceId().equals(castOther.getTestPriceId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getTestPriceId() == null ? 0 : this.getTestPriceId().hashCode());

        return result;
    }

    public String getNewFlag() {
        return newFlag;
    }

    public void setNewFlag(String newFlag) {
        this.newFlag = newFlag;
    }

    public String getUpdateFlag() {
        return updateFlag;
    }

    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag;
    }

}
