package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * VesselType generated by hbm2java
 */
public class VesselType  implements java.io.Serializable {

    // Fields    

     private VesselTypeId vesselTypeId;
     @Length(min=0, max=450) private String rbKey;
     @Length(min=0, max=450) private String rbValue;
     private Integer vesselFlag;
     private Date endDate;

     // Constructors

    /** default constructor */
    public VesselType() {
    }

	/** minimal constructor */
    public VesselType(VesselTypeId vesselTypeId) {
        this.vesselTypeId = vesselTypeId;
    }
    /** full constructor */
    public VesselType(VesselTypeId vesselTypeId, String rbKey, String rbValue, Integer vesselFlag, Date endDate) {
       this.vesselTypeId = vesselTypeId;
       this.rbKey = rbKey;
       this.rbValue = rbValue;
       this.vesselFlag = vesselFlag;
       this.endDate = endDate;
    }
   
    // Property accessors
    public VesselTypeId getVesselTypeId() {
        return this.vesselTypeId;
    }
    
    public void setVesselTypeId(VesselTypeId vesselTypeId) {
        this.vesselTypeId = vesselTypeId;
    }
    public String getRbKey() {
        return this.rbKey;
    }
    
    public void setRbKey(String rbKey) {
        this.rbKey = rbKey;
    }
    public String getRbValue() {
        return this.rbValue;
    }
    
    public void setRbValue(String rbValue) {
        this.rbValue = rbValue;
    }
    public Integer getVesselFlag() {
        return this.vesselFlag;
    }
    
    public void setVesselFlag(Integer vesselFlag) {
        this.vesselFlag = vesselFlag;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VesselType) ) return false;
		 VesselType castOther = ( VesselType ) other; 
         
		 return ( (this.getVesselTypeId()==castOther.getVesselTypeId()) || ( this.getVesselTypeId()!=null && castOther.getVesselTypeId()!=null && this.getVesselTypeId().equals(castOther.getVesselTypeId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getVesselTypeId() == null ? 0 : this.getVesselTypeId().hashCode() );
         
         
         
         
         return result;
   }   


}


