package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * BankLanguage generated by hbm2java
 */
public class BankLanguage  implements java.io.Serializable {

    // Fields    

     private BankLanguageId bankLanguageId;
     @NotBlank String bankDesc;
     private String address1;
     private String address2;
     private String address3;
     private String address4;
     private String city;
     private String postal;
     private Bank bank;

     // Constructors

    /** default constructor */
    public BankLanguage() {
    }

	/** minimal constructor */
    public BankLanguage(BankLanguageId bankLanguageId, String bankDesc) {
        this.bankLanguageId = bankLanguageId;
        this.bankDesc = bankDesc;
    }
    /** full constructor */
    public BankLanguage(BankLanguageId bankLanguageId, String bankDesc, String address1, String address2, String address3, String address4, String city, String postal, Bank bank) {
       this.bankLanguageId = bankLanguageId;
       this.bankDesc = bankDesc;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.address4 = address4;
       this.city = city;
       this.postal = postal;
       this.bank = bank;
    }
   
    // Property accessors
    public BankLanguageId getBankLanguageId() {
        return this.bankLanguageId;
    }
    
    public void setBankLanguageId(BankLanguageId bankLanguageId) {
        this.bankLanguageId = bankLanguageId;
    }
    public String getBankDesc() {
        return this.bankDesc;
    }
    
    public void setBankDesc(String bankDesc) {
        this.bankDesc = bankDesc;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }
    public String getAddress4() {
        return this.address4;
    }
    
    public void setAddress4(String address4) {
        this.address4 = address4;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPostal() {
        return this.postal;
    }
    
    public void setPostal(String postal) {
        this.postal = postal;
    }
    public Bank getBank() {
        return this.bank;
    }
    
    public void setBank(Bank bank) {
        this.bank = bank;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BankLanguage) ) return false;
		 BankLanguage castOther = ( BankLanguage ) other; 
         
		 return ( (this.getBankLanguageId()==castOther.getBankLanguageId()) || ( this.getBankLanguageId()!=null && castOther.getBankLanguageId()!=null && this.getBankLanguageId().equals(castOther.getBankLanguageId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBankLanguageId() == null ? 0 : this.getBankLanguageId().hashCode() );
         
         
         
         
         
         
         
         
         return result;
   }   


}


