package com.intertek.entity;

// Generated by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.springmodules.validation.bean.conf.loader.annotation.handler.Email;
import org.springmodules.validation.bean.conf.loader.annotation.handler.Length;
import org.springmodules.validation.bean.conf.loader.annotation.handler.NotBlank;

import com.intertek.phoenix.entity.Collectable;

/**
 * Branch generated by hbm2java
 */
@Entity
public class Branch implements java.io.Serializable, Collectable {

    // Fields
    @Id
    @NotBlank
    @Length(min = 0, max = 8)
    private String name;
    @NotBlank
    @Length(min = 0, max = 512)
    private String description;
    @Length(min = 0, max = 1)
    private String status;
    @Length(min = 0, max = 4)
    private String type;
    @Length(min = 0, max = 55)
    private String address1;
    @Length(min = 0, max = 55)
    private String address2;
    @Length(min = 0, max = 55)
    private String address3;
    @Length(min = 0, max = 55)
    private String address4;
    @Length(min = 0, max = 30)
    private String city;
    @Length(min = 0, max = 6)
    private String num1;
    @Length(min = 0, max = 4)
    private String num2;
    @Length(min = 0, max = 2)
    private String houseType;
    @Length(min = 0, max = 2)
    private String addrField1;
    @Length(min = 0, max = 4)
    private String addrField2;
    @Length(min = 0, max = 4)
    private String addrField3;
    @Length(min = 0, max = 30)
    private String county;
    @Length(min = 0, max = 12)
    private String postal;
    @Length(min = 0, max = 3)
    private String phonePrefix;
    @Length(min = 0, max = 24)
    private String phoneNumber;
    @Length(min = 0, max = 6)
    private String phoneExtension;
    @Length(min = 0, max = 30)
    private String fax;
    @Email
    @Length(min = 0, max = 70)
    private String branchEmail;
    @Length(min = 0, max = 30)
    private String logoName;
    @Length(min = 0, max = 150)
    private String companyDesc;
    @Length(min = 0, max = 6)
    private String stateCode;
    @NotBlank
    @Length(min = 0, max = 3)
    private String countryCode;
    private double seqNumber;
    private Country country;
    private State state;
    @NotBlank
    @Length(min = 0, max = 5)
    private String buName;

    @ManyToOne
    @JoinColumn(name = "BU_NAME")
    private BusinessUnit businessUnit;
    @Length(min = 0, max = 8)
    private String opsBranchName;
    @Length(min = 0, max = 8)
    private String labBranchName;
    @Length(min = 0, max = 8)
    private String vatBranchName;
    @Length(min = 0, max = 6)
    private String numberCategory;
    @Length(min = 0, max = 8)
    private String timezone;
    @Length(min = 0, max = 8)
    private String newFlag;
    @Length(min = 0, max = 8)
    private String updateFlag;
    private TimeZone timeZone;
    private Branch opsBranch;
    private Branch labBranch;
    private Branch vatBranch;
    private Set<User> users = new HashSet<User>(0);
    private Set<AssocBranch> assocBranch = new HashSet<AssocBranch>(0);

    private String serviceLocationCode;
    @ManyToOne
    @JoinColumn(name = "SERVICE_LOCATION_CODE")
    private ServiceLocation serviceLocation;

    // Constructors

    /** default constructor */
    public Branch() {
    }

    /** minimal constructor */
    public Branch(String name, String countryCode, String buName) {
        this.name = name;
        this.countryCode = countryCode;
        this.buName = buName;
    }

    /** full constructor */
    public Branch(String name, String description, String status, String type, String address1, String address2, String address3, String address4, String city,
            String num1, String num2, String houseType, String addrField1, String addrField2, String addrField3, String county, String postal,
            String phonePrefix, String phoneNumber, String phoneExtension, String fax, String branchEmail, String logoName, String companyDesc,
            String stateCode, String countryCode, double seqNumber, Country country, State state, String buName, BusinessUnit businessUnit,
            String opsBranchName, String labBranchName, String vatBranchName, String numberCategory, String timezone, String newFlag, String updateFlag,
            TimeZone timeZone, Branch opsBranch, Branch labBranch, Branch vatBranch, Set<User> users, Set<AssocBranch> assocBranch) {
        this.name = name;
        this.description = description;
        this.status = status;
        this.type = type;
        this.address1 = address1;
        this.address2 = address2;
        this.address3 = address3;
        this.address4 = address4;
        this.city = city;
        this.num1 = num1;
        this.num2 = num2;
        this.houseType = houseType;
        this.addrField1 = addrField1;
        this.addrField2 = addrField2;
        this.addrField3 = addrField3;
        this.county = county;
        this.postal = postal;
        this.phonePrefix = phonePrefix;
        this.phoneNumber = phoneNumber;
        this.phoneExtension = phoneExtension;
        this.fax = fax;
        this.branchEmail = branchEmail;
        this.logoName = logoName;
        this.companyDesc = companyDesc;
        this.stateCode = stateCode;
        this.countryCode = countryCode;
        this.seqNumber = seqNumber;
        this.country = country;
        this.state = state;
        this.buName = buName;
        this.businessUnit = businessUnit;
        this.opsBranchName = opsBranchName;
        this.labBranchName = labBranchName;
        this.vatBranchName = vatBranchName;
        this.numberCategory = numberCategory;
        this.timezone = timezone;
        this.newFlag = newFlag;
        this.updateFlag = updateFlag;
        this.timeZone = timeZone;
        this.opsBranch = opsBranch;
        this.labBranch = labBranch;
        this.vatBranch = vatBranch;
        this.users = users;
        this.assocBranch = assocBranch;
    }

    // Property accessors
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getAddress3() {
        return this.address3;
    }

    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    public String getAddress4() {
        return this.address4;
    }

    public void setAddress4(String address4) {
        this.address4 = address4;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getNum1() {
        return this.num1;
    }

    public void setNum1(String num1) {
        this.num1 = num1;
    }

    public String getNum2() {
        return this.num2;
    }

    public void setNum2(String num2) {
        this.num2 = num2;
    }

    public String getHouseType() {
        return this.houseType;
    }

    public void setHouseType(String houseType) {
        this.houseType = houseType;
    }

    public String getAddrField1() {
        return this.addrField1;
    }

    public void setAddrField1(String addrField1) {
        this.addrField1 = addrField1;
    }

    public String getAddrField2() {
        return this.addrField2;
    }

    public void setAddrField2(String addrField2) {
        this.addrField2 = addrField2;
    }

    public String getAddrField3() {
        return this.addrField3;
    }

    public void setAddrField3(String addrField3) {
        this.addrField3 = addrField3;
    }

    public String getCounty() {
        return this.county;
    }

    public void setCounty(String county) {
        this.county = county;
    }

    public String getPostal() {
        return this.postal;
    }

    public void setPostal(String postal) {
        this.postal = postal;
    }

    public String getPhonePrefix() {
        return this.phonePrefix;
    }

    public void setPhonePrefix(String phonePrefix) {
        this.phonePrefix = phonePrefix;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getPhoneExtension() {
        return this.phoneExtension;
    }

    public void setPhoneExtension(String phoneExtension) {
        this.phoneExtension = phoneExtension;
    }

    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getBranchEmail() {
        return this.branchEmail;
    }

    public void setBranchEmail(String branchEmail) {
        this.branchEmail = branchEmail;
    }

    public String getLogoName() {
        return this.logoName;
    }

    public void setLogoName(String logoName) {
        this.logoName = logoName;
    }

    public String getCompanyDesc() {
        return this.companyDesc;
    }

    public void setCompanyDesc(String companyDesc) {
        this.companyDesc = companyDesc;
    }

    public String getStateCode() {
        return this.stateCode;
    }

    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }

    public String getCountryCode() {
        return this.countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public double getSeqNumber() {
        return this.seqNumber;
    }

    public void setSeqNumber(double seqNumber) {
        this.seqNumber = seqNumber;
    }

    public Country getCountry() {
        return this.country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    public State getState() {
        return this.state;
    }

    public void setState(State state) {
        this.state = state;
    }

    public String getBuName() {
        return this.buName;
    }

    public void setBuName(String buName) {
        this.buName = buName;
    }

    public BusinessUnit getBusinessUnit() {
        return this.businessUnit;
    }

    public void setBusinessUnit(BusinessUnit businessUnit) {
        this.businessUnit = businessUnit;
    }

    public String getOpsBranchName() {
        return this.opsBranchName;
    }

    public void setOpsBranchName(String opsBranchName) {
        this.opsBranchName = opsBranchName;
    }

    public String getLabBranchName() {
        return this.labBranchName;
    }

    public void setLabBranchName(String labBranchName) {
        this.labBranchName = labBranchName;
    }

    public String getVatBranchName() {
        return this.vatBranchName;
    }

    public void setVatBranchName(String vatBranchName) {
        this.vatBranchName = vatBranchName;
    }

    public String getNumberCategory() {
        return this.numberCategory;
    }

    public void setNumberCategory(String numberCategory) {
        this.numberCategory = numberCategory;
    }

    public String getTimezone() {
        return this.timezone;
    }

    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    public String getNewFlag() {
        return this.newFlag;
    }

    public void setNewFlag(String newFlag) {
        this.newFlag = newFlag;
    }

    public String getUpdateFlag() {
        return this.updateFlag;
    }

    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag;
    }

    public TimeZone getTimeZone() {
        return this.timeZone;
    }

    public void setTimeZone(TimeZone timeZone) {
        this.timeZone = timeZone;
    }

    public Branch getOpsBranch() {
        return this.opsBranch;
    }

    public void setOpsBranch(Branch opsBranch) {
        this.opsBranch = opsBranch;
    }

    public Branch getLabBranch() {
        return this.labBranch;
    }

    public void setLabBranch(Branch labBranch) {
        this.labBranch = labBranch;
    }

    public Branch getVatBranch() {
        return this.vatBranch;
    }

    public void setVatBranch(Branch vatBranch) {
        this.vatBranch = vatBranch;
    }

    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }

    public Set<AssocBranch> getAssocBranch() {
        return this.assocBranch;
    }

    public void setAssocBranch(Set<AssocBranch> assocBranch) {
        this.assocBranch = assocBranch;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof Branch))
            return false;
        Branch castOther = (Branch) other;

        return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this.getName().equals(castOther.getName())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());

        return result;
    }

    public ServiceLocation getServiceLocation() {
        return serviceLocation;
    }

    public void setServiceLocation(ServiceLocation serviceLocation) {
        this.serviceLocation = serviceLocation;
    }

    public String getServiceLocationCode() {
        return serviceLocationCode;
    }

    public void setServiceLocationCode(String serviceLocationCode) {
        this.serviceLocationCode = serviceLocationCode;
    }

}
