package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * BusinessUnitLanguageId generated by hbm2java
 */
public class BusinessUnitLanguageId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=5) private String name;
     @NotBlank @Length(min=0, max=9) private String languageCD;

     // Constructors

    /** default constructor */
    public BusinessUnitLanguageId() {
    }

    /** full constructor */
    public BusinessUnitLanguageId(String name, String languageCD) {
       this.name = name;
       this.languageCD = languageCD;
    }
   
    // Property accessors
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLanguageCD() {
        return this.languageCD;
    }
    
    public void setLanguageCD(String languageCD) {
        this.languageCD = languageCD;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BusinessUnitLanguageId) ) return false;
		 BusinessUnitLanguageId castOther = ( BusinessUnitLanguageId ) other; 
         
		 return ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getLanguageCD()==castOther.getLanguageCD()) || ( this.getLanguageCD()!=null && castOther.getLanguageCD()!=null && this.getLanguageCD().equals(castOther.getLanguageCD()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getLanguageCD() == null ? 0 : this.getLanguageCD().hashCode() );
         return result;
   }   


}


