package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * BusUnitVatLocId generated by hbm2java
 */
public class BusUnitVatLocId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=3) private String countryCode;
     @NotBlank @Length(min=0, max=5) private String buName;
     @NotBlank @Length(min=0, max=12) private String vatRegistrationId;

     // Constructors

    /** default constructor */
    public BusUnitVatLocId() {
    }

    /** full constructor */
    public BusUnitVatLocId(String countryCode, String buName, String vatRegistrationId) {
       this.countryCode = countryCode;
       this.buName = buName;
       this.vatRegistrationId = vatRegistrationId;
    }
   
    // Property accessors
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getBuName() {
        return this.buName;
    }
    
    public void setBuName(String buName) {
        this.buName = buName;
    }
    public String getVatRegistrationId() {
        return this.vatRegistrationId;
    }
    
    public void setVatRegistrationId(String vatRegistrationId) {
        this.vatRegistrationId = vatRegistrationId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BusUnitVatLocId) ) return false;
		 BusUnitVatLocId castOther = ( BusUnitVatLocId ) other; 
         
		 return ( (this.getCountryCode()==castOther.getCountryCode()) || ( this.getCountryCode()!=null && castOther.getCountryCode()!=null && this.getCountryCode().equals(castOther.getCountryCode()) ) )
 && ( (this.getBuName()==castOther.getBuName()) || ( this.getBuName()!=null && castOther.getBuName()!=null && this.getBuName().equals(castOther.getBuName()) ) )
 && ( (this.getVatRegistrationId()==castOther.getVatRegistrationId()) || ( this.getVatRegistrationId()!=null && castOther.getVatRegistrationId()!=null && this.getVatRegistrationId().equals(castOther.getVatRegistrationId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCountryCode() == null ? 0 : this.getCountryCode().hashCode() );
         result = 37 * result + ( getBuName() == null ? 0 : this.getBuName().hashCode() );
         result = 37 * result + ( getVatRegistrationId() == null ? 0 : this.getVatRegistrationId().hashCode() );
         return result;
   }   


}


