package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ConsolidatedInvoice generated by hbm2java
 */
public class ConsolidatedInvoice  implements java.io.Serializable {

    // Fields    

     private ConsolidatedInvoiceId consolidatedInvoiceId;
     @NotBlank @Length(min=0, max=15) private String custCode;
     @Length(min=0, max=3) private String billStatus;
     @Length(min=0, max=3) private String billType;
     @Length(min=0, max=3) private String currencyCd;
     @Length(min=0, max=3) private String invoiceType;
     private Date billAddDt;
     private Date fromDt;
     private Date toDt;
     private Date invoiceDt;
     @Length(min=0, max=5) private String pymntTermsCd;
     @Length(min=0, max=5) private String bankCd;
     @Length(min=0, max=4) private String bankAcctKey;
     private Double invoiceAmtPreTax;
     private Double invoiceAmtPostTax;
     @Length(min=0, max=22) private String invoice;
     private Integer locationNumber;
     @Length(min=0, max=8) private String sentToFinFlag;
     private Date generateTime;
     @Length(min=0, max=80) private String invoiceFileName;
     private Boolean pdfGeneratedFlag;
     @Length(min=0, max=20) private String vatProvince;
     @Length(min=0, max=128) private String generatedByUserName;
     private User generatedBy;
     private Customer customer;
     private Contact contact;
     private CustAddrSeq custAddrSeq;
     private ContactCust contactCust;
     private BusinessUnit businessUnit;
     private PaymentTerm paymentTerm;
     private Set<JobContractInvoice> jobContractInvoices = new HashSet<JobContractInvoice>(0);
     private Set<ConsolInvoiceFile> consolInvoiceFiles = new HashSet<ConsolInvoiceFile>(0);

     // Constructors

    /** default constructor */
    public ConsolidatedInvoice() {
    }

	/** minimal constructor */
    public ConsolidatedInvoice(ConsolidatedInvoiceId consolidatedInvoiceId) {
        this.consolidatedInvoiceId = consolidatedInvoiceId;
    }
    /** full constructor */
    public ConsolidatedInvoice(ConsolidatedInvoiceId consolidatedInvoiceId, String custCode, String billStatus, String billType, String currencyCd, String invoiceType, Date billAddDt, Date fromDt, Date toDt, Date invoiceDt, String pymntTermsCd, String bankCd, String bankAcctKey, Double invoiceAmtPreTax, Double invoiceAmtPostTax, String invoice, Integer locationNumber, String sentToFinFlag, Date generateTime, String invoiceFileName, Boolean pdfGeneratedFlag, String vatProvince, String generatedByUserName, User generatedBy, Customer customer, Contact contact, CustAddrSeq custAddrSeq, ContactCust contactCust, BusinessUnit businessUnit, PaymentTerm paymentTerm, Set<JobContractInvoice> jobContractInvoices, Set<ConsolInvoiceFile> consolInvoiceFiles) {
       this.consolidatedInvoiceId = consolidatedInvoiceId;
       this.custCode = custCode;
       this.billStatus = billStatus;
       this.billType = billType;
       this.currencyCd = currencyCd;
       this.invoiceType = invoiceType;
       this.billAddDt = billAddDt;
       this.fromDt = fromDt;
       this.toDt = toDt;
       this.invoiceDt = invoiceDt;
       this.pymntTermsCd = pymntTermsCd;
       this.bankCd = bankCd;
       this.bankAcctKey = bankAcctKey;
       this.invoiceAmtPreTax = invoiceAmtPreTax;
       this.invoiceAmtPostTax = invoiceAmtPostTax;
       this.invoice = invoice;
       this.locationNumber = locationNumber;
       this.sentToFinFlag = sentToFinFlag;
       this.generateTime = generateTime;
       this.invoiceFileName = invoiceFileName;
       this.pdfGeneratedFlag = pdfGeneratedFlag;
       this.vatProvince = vatProvince;
       this.generatedByUserName = generatedByUserName;
       this.generatedBy = generatedBy;
       this.customer = customer;
       this.contact = contact;
       this.custAddrSeq = custAddrSeq;
       this.contactCust = contactCust;
       this.businessUnit = businessUnit;
       this.paymentTerm = paymentTerm;
       this.jobContractInvoices = jobContractInvoices;
       this.consolInvoiceFiles = consolInvoiceFiles;
    }
   
    // Property accessors
    public ConsolidatedInvoiceId getConsolidatedInvoiceId() {
        return this.consolidatedInvoiceId;
    }
    
    public void setConsolidatedInvoiceId(ConsolidatedInvoiceId consolidatedInvoiceId) {
        this.consolidatedInvoiceId = consolidatedInvoiceId;
    }
    public String getCustCode() {
        return this.custCode;
    }
    
    public void setCustCode(String custCode) {
        this.custCode = custCode;
    }
    public String getBillStatus() {
        return this.billStatus;
    }
    
    public void setBillStatus(String billStatus) {
        this.billStatus = billStatus;
    }
    public String getBillType() {
        return this.billType;
    }
    
    public void setBillType(String billType) {
        this.billType = billType;
    }
    public String getCurrencyCd() {
        return this.currencyCd;
    }
    
    public void setCurrencyCd(String currencyCd) {
        this.currencyCd = currencyCd;
    }
    public String getInvoiceType() {
        return this.invoiceType;
    }
    
    public void setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType;
    }
    public Date getBillAddDt() {
        return this.billAddDt;
    }
    
    public void setBillAddDt(Date billAddDt) {
        this.billAddDt = billAddDt;
    }
    public Date getFromDt() {
        return this.fromDt;
    }
    
    public void setFromDt(Date fromDt) {
        this.fromDt = fromDt;
    }
    public Date getToDt() {
        return this.toDt;
    }
    
    public void setToDt(Date toDt) {
        this.toDt = toDt;
    }
    public Date getInvoiceDt() {
        return this.invoiceDt;
    }
    
    public void setInvoiceDt(Date invoiceDt) {
        this.invoiceDt = invoiceDt;
    }
    public String getPymntTermsCd() {
        return this.pymntTermsCd;
    }
    
    public void setPymntTermsCd(String pymntTermsCd) {
        this.pymntTermsCd = pymntTermsCd;
    }
    public String getBankCd() {
        return this.bankCd;
    }
    
    public void setBankCd(String bankCd) {
        this.bankCd = bankCd;
    }
    public String getBankAcctKey() {
        return this.bankAcctKey;
    }
    
    public void setBankAcctKey(String bankAcctKey) {
        this.bankAcctKey = bankAcctKey;
    }
    public Double getInvoiceAmtPreTax() {
        return this.invoiceAmtPreTax;
    }
    
    public void setInvoiceAmtPreTax(Double invoiceAmtPreTax) {
        this.invoiceAmtPreTax = invoiceAmtPreTax;
    }
    public Double getInvoiceAmtPostTax() {
        return this.invoiceAmtPostTax;
    }
    
    public void setInvoiceAmtPostTax(Double invoiceAmtPostTax) {
        this.invoiceAmtPostTax = invoiceAmtPostTax;
    }
    public String getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(String invoice) {
        this.invoice = invoice;
    }
    public Integer getLocationNumber() {
        return this.locationNumber;
    }
    
    public void setLocationNumber(Integer locationNumber) {
        this.locationNumber = locationNumber;
    }
    public String getSentToFinFlag() {
        return this.sentToFinFlag;
    }
    
    public void setSentToFinFlag(String sentToFinFlag) {
        this.sentToFinFlag = sentToFinFlag;
    }
    public Date getGenerateTime() {
        return this.generateTime;
    }
    
    public void setGenerateTime(Date generateTime) {
        this.generateTime = generateTime;
    }
    public String getInvoiceFileName() {
        return this.invoiceFileName;
    }
    
    public void setInvoiceFileName(String invoiceFileName) {
        this.invoiceFileName = invoiceFileName;
    }
    public Boolean getPdfGeneratedFlag() {
        return this.pdfGeneratedFlag;
    }
    
    public void setPdfGeneratedFlag(Boolean pdfGeneratedFlag) {
        this.pdfGeneratedFlag = pdfGeneratedFlag;
    }
    public String getVatProvince() {
        return this.vatProvince;
    }
    
    public void setVatProvince(String vatProvince) {
        this.vatProvince = vatProvince;
    }
    public String getGeneratedByUserName() {
        return this.generatedByUserName;
    }
    
    public void setGeneratedByUserName(String generatedByUserName) {
        this.generatedByUserName = generatedByUserName;
    }
    public User getGeneratedBy() {
        return this.generatedBy;
    }
    
    public void setGeneratedBy(User generatedBy) {
        this.generatedBy = generatedBy;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public CustAddrSeq getCustAddrSeq() {
        return this.custAddrSeq;
    }
    
    public void setCustAddrSeq(CustAddrSeq custAddrSeq) {
        this.custAddrSeq = custAddrSeq;
    }
    public ContactCust getContactCust() {
        return this.contactCust;
    }
    
    public void setContactCust(ContactCust contactCust) {
        this.contactCust = contactCust;
    }
    public BusinessUnit getBusinessUnit() {
        return this.businessUnit;
    }
    
    public void setBusinessUnit(BusinessUnit businessUnit) {
        this.businessUnit = businessUnit;
    }
    public PaymentTerm getPaymentTerm() {
        return this.paymentTerm;
    }
    
    public void setPaymentTerm(PaymentTerm paymentTerm) {
        this.paymentTerm = paymentTerm;
    }
    public Set<JobContractInvoice> getJobContractInvoices() {
        return this.jobContractInvoices;
    }
    
    public void setJobContractInvoices(Set<JobContractInvoice> jobContractInvoices) {
        this.jobContractInvoices = jobContractInvoices;
    }
    public Set<ConsolInvoiceFile> getConsolInvoiceFiles() {
        return this.consolInvoiceFiles;
    }
    
    public void setConsolInvoiceFiles(Set<ConsolInvoiceFile> consolInvoiceFiles) {
        this.consolInvoiceFiles = consolInvoiceFiles;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConsolidatedInvoice) ) return false;
		 ConsolidatedInvoice castOther = ( ConsolidatedInvoice ) other; 
         
		 return ( (this.getConsolidatedInvoiceId()==castOther.getConsolidatedInvoiceId()) || ( this.getConsolidatedInvoiceId()!=null && castOther.getConsolidatedInvoiceId()!=null && this.getConsolidatedInvoiceId().equals(castOther.getConsolidatedInvoiceId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getConsolidatedInvoiceId() == null ? 0 : this.getConsolidatedInvoiceId().hashCode() );
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         return result;
   }   


}


