package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ControlSwitchId generated by hbm2java
 */
public class ControlSwitchId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=100) private String controlSwitchName;
     @NotBlank @Length(min=0, max=100) private String controlSwitchType;

     // Constructors

    /** default constructor */
    public ControlSwitchId() {
    }

    /** full constructor */
    public ControlSwitchId(String controlSwitchName, String controlSwitchType) {
       this.controlSwitchName = controlSwitchName;
       this.controlSwitchType = controlSwitchType;
    }
   
    // Property accessors
    public String getControlSwitchName() {
        return this.controlSwitchName;
    }
    
    public void setControlSwitchName(String controlSwitchName) {
        this.controlSwitchName = controlSwitchName;
    }
    public String getControlSwitchType() {
        return this.controlSwitchType;
    }
    
    public void setControlSwitchType(String controlSwitchType) {
        this.controlSwitchType = controlSwitchType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ControlSwitchId) ) return false;
		 ControlSwitchId castOther = ( ControlSwitchId ) other; 
         
		 return ( (this.getControlSwitchName()==castOther.getControlSwitchName()) || ( this.getControlSwitchName()!=null && castOther.getControlSwitchName()!=null && this.getControlSwitchName().equals(castOther.getControlSwitchName()) ) )
 && ( (this.getControlSwitchType()==castOther.getControlSwitchType()) || ( this.getControlSwitchType()!=null && castOther.getControlSwitchType()!=null && this.getControlSwitchType().equals(castOther.getControlSwitchType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getControlSwitchName() == null ? 0 : this.getControlSwitchName().hashCode() );
         result = 37 * result + ( getControlSwitchType() == null ? 0 : this.getControlSwitchType().hashCode() );
         return result;
   }   


}


