package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ControlMap generated by hbm2java
 */
public class ControlMap  implements java.io.Serializable {

    // Fields    

     private ControlMapId controlMapId;

     // Constructors

    /** default constructor */
    public ControlMap() {
    }

    /** full constructor */
    public ControlMap(ControlMapId controlMapId) {
       this.controlMapId = controlMapId;
    }
   
    // Property accessors
    public ControlMapId getControlMapId() {
        return this.controlMapId;
    }
    
    public void setControlMapId(ControlMapId controlMapId) {
        this.controlMapId = controlMapId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ControlMap) ) return false;
		 ControlMap castOther = ( ControlMap ) other; 
         
		 return ( (this.getControlMapId()==castOther.getControlMapId()) || ( this.getControlMapId()!=null && castOther.getControlMapId()!=null && this.getControlMapId().equals(castOther.getControlMapId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getControlMapId() == null ? 0 : this.getControlMapId().hashCode() );
         return result;
   }   


}


