package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * CountryVATId generated by hbm2java
 */
public class CountryVATId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=3) private String countryCode;
     @NotBlank @Length(min=0, max=6) private String stateCode;
     private Date effDate;

     // Constructors

    /** default constructor */
    public CountryVATId() {
    }

    /** full constructor */
    public CountryVATId(String countryCode, String stateCode, Date effDate) {
       this.countryCode = countryCode;
       this.stateCode = stateCode;
       this.effDate = effDate;
    }
   
    // Property accessors
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getStateCode() {
        return this.stateCode;
    }
    
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }
    public Date getEffDate() {
        return this.effDate;
    }
    
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CountryVATId) ) return false;
		 CountryVATId castOther = ( CountryVATId ) other; 
         
		 return ( (this.getCountryCode()==castOther.getCountryCode()) || ( this.getCountryCode()!=null && castOther.getCountryCode()!=null && this.getCountryCode().equals(castOther.getCountryCode()) ) )
 && ( (this.getStateCode()==castOther.getStateCode()) || ( this.getStateCode()!=null && castOther.getStateCode()!=null && this.getStateCode().equals(castOther.getStateCode()) ) )
 && ( (this.getEffDate()==castOther.getEffDate()) || ( this.getEffDate()!=null && castOther.getEffDate()!=null && this.getEffDate().equals(castOther.getEffDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCountryCode() == null ? 0 : this.getCountryCode().hashCode() );
         result = 37 * result + ( getStateCode() == null ? 0 : this.getStateCode().hashCode() );
         result = 37 * result + ( getEffDate() == null ? 0 : this.getEffDate().hashCode() );
         return result;
   }   


}


