package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * CustVatRegistration generated by hbm2java
 */
public class CustVatRegistration  implements java.io.Serializable {

    // Fields    

     private CustVatRegistrationId custVatRegistrationId;
     private Boolean homeCountryInd;
     private Customer customer;
     private Country country;
     @Length(min=0, max=6) private String state;

     // Constructors

    /** default constructor */
    public CustVatRegistration() {
    }

	/** minimal constructor */
    public CustVatRegistration(CustVatRegistrationId custVatRegistrationId) {
        this.custVatRegistrationId = custVatRegistrationId;
    }
    /** full constructor */
    public CustVatRegistration(CustVatRegistrationId custVatRegistrationId, Boolean homeCountryInd, Customer customer, Country country, String state) {
       this.custVatRegistrationId = custVatRegistrationId;
       this.homeCountryInd = homeCountryInd;
       this.customer = customer;
       this.country = country;
       this.state = state;
    }
   
    // Property accessors
    public CustVatRegistrationId getCustVatRegistrationId() {
        return this.custVatRegistrationId;
    }
    
    public void setCustVatRegistrationId(CustVatRegistrationId custVatRegistrationId) {
        this.custVatRegistrationId = custVatRegistrationId;
    }
    public Boolean getHomeCountryInd() {
        return this.homeCountryInd;
    }
    
    public void setHomeCountryInd(Boolean homeCountryInd) {
        this.homeCountryInd = homeCountryInd;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CustVatRegistration) ) return false;
		 CustVatRegistration castOther = ( CustVatRegistration ) other; 
         
		 return ( (this.getCustVatRegistrationId()==castOther.getCustVatRegistrationId()) || ( this.getCustVatRegistrationId()!=null && castOther.getCustVatRegistrationId()!=null && this.getCustVatRegistrationId().equals(castOther.getCustVatRegistrationId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCustVatRegistrationId() == null ? 0 : this.getCustVatRegistrationId().hashCode() );
         
         
         
         
         return result;
   }   


}


