package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * CustomerLanguageId generated by hbm2java
 */
public class CustomerLanguageId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=15) private String custCode;
     @NotBlank @Length(min=0, max=9) private String languageCD;

     // Constructors

    /** default constructor */
    public CustomerLanguageId() {
    }

    /** full constructor */
    public CustomerLanguageId(String custCode, String languageCD) {
       this.custCode = custCode;
       this.languageCD = languageCD;
    }
   
    // Property accessors
    public String getCustCode() {
        return this.custCode;
    }
    
    public void setCustCode(String custCode) {
        this.custCode = custCode;
    }
    public String getLanguageCD() {
        return this.languageCD;
    }
    
    public void setLanguageCD(String languageCD) {
        this.languageCD = languageCD;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CustomerLanguageId) ) return false;
		 CustomerLanguageId castOther = ( CustomerLanguageId ) other; 
         
		 return ( (this.getCustCode()==castOther.getCustCode()) || ( this.getCustCode()!=null && castOther.getCustCode()!=null && this.getCustCode().equals(castOther.getCustCode()) ) )
 && ( (this.getLanguageCD()==castOther.getLanguageCD()) || ( this.getLanguageCD()!=null && castOther.getLanguageCD()!=null && this.getLanguageCD().equals(castOther.getLanguageCD()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCustCode() == null ? 0 : this.getCustCode().hashCode() );
         result = 37 * result + ( getLanguageCD() == null ? 0 : this.getLanguageCD().hashCode() );
         return result;
   }   


}


