package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * CustAddrSeq generated by hbm2java
 */
public class CustAddrSeq  implements java.io.Serializable {

    // Fields    

     private CustAddrSeqId custAddrSeqId;
     private Customer customer;
     @NotBlank @Length(min=0, max=30) private String addressDescr;
     private Boolean corresponence;
     private Boolean billTo;
     private Boolean soldTo;
     private Boolean shipTo;
     private Set<ContactCust> contactCusts = new HashSet<ContactCust>(0);
     private Set<CustAddress> custAddresses = new HashSet<CustAddress>(0);

     // Constructors

    /** default constructor */
    public CustAddrSeq() {
    }

	/** minimal constructor */
    public CustAddrSeq(CustAddrSeqId custAddrSeqId) {
        this.custAddrSeqId = custAddrSeqId;
    }
    /** full constructor */
    public CustAddrSeq(CustAddrSeqId custAddrSeqId, Customer customer, String addressDescr, Boolean corresponence, Boolean billTo, Boolean soldTo, Boolean shipTo, Set<ContactCust> contactCusts, Set<CustAddress> custAddresses) {
       this.custAddrSeqId = custAddrSeqId;
       this.customer = customer;
       this.addressDescr = addressDescr;
       this.corresponence = corresponence;
       this.billTo = billTo;
       this.soldTo = soldTo;
       this.shipTo = shipTo;
       this.contactCusts = contactCusts;
       this.custAddresses = custAddresses;
    }
   
    // Property accessors
    public CustAddrSeqId getCustAddrSeqId() {
        return this.custAddrSeqId;
    }
    
    public void setCustAddrSeqId(CustAddrSeqId custAddrSeqId) {
        this.custAddrSeqId = custAddrSeqId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getAddressDescr() {
        return this.addressDescr;
    }
    
    public void setAddressDescr(String addressDescr) {
        this.addressDescr = addressDescr;
    }
    public Boolean getCorresponence() {
        return this.corresponence;
    }
    
    public void setCorresponence(Boolean corresponence) {
        this.corresponence = corresponence;
    }
    public Boolean getBillTo() {
        return this.billTo;
    }
    
    public void setBillTo(Boolean billTo) {
        this.billTo = billTo;
    }
    public Boolean getSoldTo() {
        return this.soldTo;
    }
    
    public void setSoldTo(Boolean soldTo) {
        this.soldTo = soldTo;
    }
    public Boolean getShipTo() {
        return this.shipTo;
    }
    
    public void setShipTo(Boolean shipTo) {
        this.shipTo = shipTo;
    }
    public Set<ContactCust> getContactCusts() {
        return this.contactCusts;
    }
    
    public void setContactCusts(Set<ContactCust> contactCusts) {
        this.contactCusts = contactCusts;
    }
    public Set<CustAddress> getCustAddresses() {
        return this.custAddresses;
    }
    
    public void setCustAddresses(Set<CustAddress> custAddresses) {
        this.custAddresses = custAddresses;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CustAddrSeq) ) return false;
		 CustAddrSeq castOther = ( CustAddrSeq ) other; 
         
		 return ( (this.getCustAddrSeqId()==castOther.getCustAddrSeqId()) || ( this.getCustAddrSeqId()!=null && castOther.getCustAddrSeqId()!=null && this.getCustAddrSeqId().equals(castOther.getCustAddrSeqId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCustAddrSeqId() == null ? 0 : this.getCustAddrSeqId().hashCode() );
         
         
         
         
         
         
         
         
         return result;
   }   


}


