package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * CustAcctTeam generated by hbm2java
 */
public class CustAcctTeam  implements java.io.Serializable {

    // Fields    

     private long id;
     @NotBlank @Length(min=0, max=1) private String accountOwnerId;
     @NotBlank @Length(min=0, max=15) private String custCode;
     private Customer customer;
     private Employee employee;

     // Constructors

    /** default constructor */
    public CustAcctTeam() {
    }

	/** minimal constructor */
    public CustAcctTeam(String custCode, Employee employee) {
        this.custCode = custCode;
        this.employee = employee;
    }
    /** full constructor */
    public CustAcctTeam(String accountOwnerId, String custCode, Customer customer, Employee employee) {
       this.accountOwnerId = accountOwnerId;
       this.custCode = custCode;
       this.customer = customer;
       this.employee = employee;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getAccountOwnerId() {
        return this.accountOwnerId;
    }
    
    public void setAccountOwnerId(String accountOwnerId) {
        this.accountOwnerId = accountOwnerId;
    }
    public String getCustCode() {
        return this.custCode;
    }
    
    public void setCustCode(String custCode) {
        this.custCode = custCode;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }




}


