package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * Expression generated by hbm2java
 */
public class Expression  implements java.io.Serializable {

    // Fields    

     private ExpressionId expressionId;
     @Length(min=0, max=9) private String expenseBranchType;

     // Constructors

    /** default constructor */
    public Expression() {
    }

	/** minimal constructor */
    public Expression(ExpressionId expressionId) {
        this.expressionId = expressionId;
    }
    /** full constructor */
    public Expression(ExpressionId expressionId, String expenseBranchType) {
       this.expressionId = expressionId;
       this.expenseBranchType = expenseBranchType;
    }
   
    // Property accessors
    public ExpressionId getExpressionId() {
        return this.expressionId;
    }
    
    public void setExpressionId(ExpressionId expressionId) {
        this.expressionId = expressionId;
    }
    public String getExpenseBranchType() {
        return this.expenseBranchType;
    }
    
    public void setExpenseBranchType(String expenseBranchType) {
        this.expenseBranchType = expenseBranchType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Expression) ) return false;
		 Expression castOther = ( Expression ) other; 
         
		 return ( (this.getExpressionId()==castOther.getExpressionId()) || ( this.getExpressionId()!=null && castOther.getExpressionId()!=null && this.getExpressionId().equals(castOther.getExpressionId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getExpressionId() == null ? 0 : this.getExpressionId().hashCode() );
         
         return result;
   }   


}


