package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * InspectionEventTbl generated by hbm2java
 */
public class InspectionEventTbl  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=128) private String name;
     @Length(min=0, max=1) private String status;
     @Length(min=0, max=512) private String instructions;
     @Length(min=0, max=3) private int sortOrder;

     // Constructors

    /** default constructor */
    public InspectionEventTbl() {
    }

	/** minimal constructor */
    public InspectionEventTbl(String name) {
        this.name = name;
    }
    /** full constructor */
    public InspectionEventTbl(String name, String status, String instructions, int sortOrder) {
       this.name = name;
       this.status = status;
       this.instructions = instructions;
       this.sortOrder = sortOrder;
    }
   
    // Property accessors
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getInstructions() {
        return this.instructions;
    }
    
    public void setInstructions(String instructions) {
        this.instructions = instructions;
    }
    public int getSortOrder() {
        return this.sortOrder;
    }
    
    public void setSortOrder(int sortOrder) {
        this.sortOrder = sortOrder;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InspectionEventTbl) ) return false;
		 InspectionEventTbl castOther = ( InspectionEventTbl ) other; 
         
		 return ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         
         
         
         return result;
   }   


}


