package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * JobContractProd generated by hbm2java
 */
public class JobContractProd  implements java.io.Serializable {

    // Fields    

     private long id;
     private JobContractVessel jobContractVessel;
     private Integer prodSeqNum;
     private String jobNumber;
     private Integer linkedVslRow;
     private Integer sampSeqId;
     private String jobProductName;
     @Length(min=0, max=256) private String destination;
     @NotBlank @Length(min=0, max=40) private String group;
     @Length(min=0, max=45) private String productGroupMaster;
     @Length(min=0, max=4) private String option;
     @Length(min=0, max=4) private String plusMinus;
     @Length(min=0, max=64) private String drafts;
     @Length(min=0, max=256) private String tanks;
     private int plusMinusPct;
     private double productQty;
     @Length(min=0, max=4) private String uom;
     private Integer sortOrderNum;
     private Boolean notChargeInd;
     private Set<JobContractProductService> jobContractProductServices = new HashSet<JobContractProductService>(0);
     private Set<JobContractProductInspectionResult> results = new HashSet<JobContractProductInspectionResult>(0);
     private Set<JobContractTest> jobContractTests = new HashSet<JobContractTest>(0);
     private Set<JobContractManualTest> jobContractManualTests = new HashSet<JobContractManualTest>(0);
     private Set<JobContractSlate> jobContractSlates = new HashSet<JobContractSlate>(0);
     private Set<JobContractProdControl> controls = new HashSet<JobContractProdControl>(0);

     // Constructors

    /** default constructor */
    public JobContractProd() {
    }

	/** minimal constructor */
    public JobContractProd(String jobProductName, String group) {
        this.jobProductName = jobProductName;
        this.group = group;
    }
    /** full constructor */
    public JobContractProd(JobContractVessel jobContractVessel, Integer prodSeqNum, String jobNumber, Integer linkedVslRow, Integer sampSeqId, String jobProductName, String destination, String group, String productGroupMaster, String option, String plusMinus, String drafts, String tanks, int plusMinusPct, double productQty, String uom, Integer sortOrderNum, Boolean notChargeInd, Set<JobContractProductService> jobContractProductServices, Set<JobContractProductInspectionResult> results, Set<JobContractTest> jobContractTests, Set<JobContractManualTest> jobContractManualTests, Set<JobContractSlate> jobContractSlates, Set<JobContractProdControl> controls) {
       this.jobContractVessel = jobContractVessel;
       this.prodSeqNum = prodSeqNum;
       this.jobNumber = jobNumber;
       this.linkedVslRow = linkedVslRow;
       this.sampSeqId = sampSeqId;
       this.jobProductName = jobProductName;
       this.destination = destination;
       this.group = group;
       this.productGroupMaster = productGroupMaster;
       this.option = option;
       this.plusMinus = plusMinus;
       this.drafts = drafts;
       this.tanks = tanks;
       this.plusMinusPct = plusMinusPct;
       this.productQty = productQty;
       this.uom = uom;
       this.sortOrderNum = sortOrderNum;
       this.notChargeInd = notChargeInd;
       this.jobContractProductServices = jobContractProductServices;
       this.results = results;
       this.jobContractTests = jobContractTests;
       this.jobContractManualTests = jobContractManualTests;
       this.jobContractSlates = jobContractSlates;
       this.controls = controls;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public JobContractVessel getJobContractVessel() {
        return this.jobContractVessel;
    }
    
    public void setJobContractVessel(JobContractVessel jobContractVessel) {
        this.jobContractVessel = jobContractVessel;
    }
    public Integer getProdSeqNum() {
        return this.prodSeqNum;
    }
    
    public void setProdSeqNum(Integer prodSeqNum) {
        this.prodSeqNum = prodSeqNum;
    }
    public String getJobNumber() {
        return this.jobNumber;
    }
    
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }
    public Integer getLinkedVslRow() {
        return this.linkedVslRow;
    }
    
    public void setLinkedVslRow(Integer linkedVslRow) {
        this.linkedVslRow = linkedVslRow;
    }
    public Integer getSampSeqId() {
        return this.sampSeqId;
    }
    
    public void setSampSeqId(Integer sampSeqId) {
        this.sampSeqId = sampSeqId;
    }
    public String getJobProductName() {
        return this.jobProductName;
    }
    
    public void setJobProductName(String jobProductName) {
        this.jobProductName = jobProductName;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public String getGroup() {
        return this.group;
    }
    
    public void setGroup(String group) {
        this.group = group;
    }
    public String getProductGroupMaster() {
        return this.productGroupMaster;
    }
    
    public void setProductGroupMaster(String productGroupMaster) {
        this.productGroupMaster = productGroupMaster;
    }
    public String getOption() {
        return this.option;
    }
    
    public void setOption(String option) {
        this.option = option;
    }
    public String getPlusMinus() {
        return this.plusMinus;
    }
    
    public void setPlusMinus(String plusMinus) {
        this.plusMinus = plusMinus;
    }
    public String getDrafts() {
        return this.drafts;
    }
    
    public void setDrafts(String drafts) {
        this.drafts = drafts;
    }
    public String getTanks() {
        return this.tanks;
    }
    
    public void setTanks(String tanks) {
        this.tanks = tanks;
    }
    public int getPlusMinusPct() {
        return this.plusMinusPct;
    }
    
    public void setPlusMinusPct(int plusMinusPct) {
        this.plusMinusPct = plusMinusPct;
    }
    public double getProductQty() {
        return this.productQty;
    }
    
    public void setProductQty(double productQty) {
        this.productQty = productQty;
    }
    public String getUom() {
        return this.uom;
    }
    
    public void setUom(String uom) {
        this.uom = uom;
    }
    public Integer getSortOrderNum() {
        return this.sortOrderNum;
    }
    
    public void setSortOrderNum(Integer sortOrderNum) {
        this.sortOrderNum = sortOrderNum;
    }
    public Boolean getNotChargeInd() {
        return this.notChargeInd;
    }
    
    public void setNotChargeInd(Boolean notChargeInd) {
        this.notChargeInd = notChargeInd;
    }
    public Set<JobContractProductService> getJobContractProductServices() {
        return this.jobContractProductServices;
    }
    
    public void setJobContractProductServices(Set<JobContractProductService> jobContractProductServices) {
        this.jobContractProductServices = jobContractProductServices;
    }
    public Set<JobContractProductInspectionResult> getResults() {
        return this.results;
    }
    
    public void setResults(Set<JobContractProductInspectionResult> results) {
        this.results = results;
    }
    public Set<JobContractTest> getJobContractTests() {
        return this.jobContractTests;
    }
    
    public void setJobContractTests(Set<JobContractTest> jobContractTests) {
        this.jobContractTests = jobContractTests;
    }
    public Set<JobContractManualTest> getJobContractManualTests() {
        return this.jobContractManualTests;
    }
    
    public void setJobContractManualTests(Set<JobContractManualTest> jobContractManualTests) {
        this.jobContractManualTests = jobContractManualTests;
    }
    public Set<JobContractSlate> getJobContractSlates() {
        return this.jobContractSlates;
    }
    
    public void setJobContractSlates(Set<JobContractSlate> jobContractSlates) {
        this.jobContractSlates = jobContractSlates;
    }
    public Set<JobContractProdControl> getControls() {
        return this.controls;
    }
    
    public void setControls(Set<JobContractProdControl> controls) {
        this.controls = controls;
    }




}


