package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * JobContractServiceResult generated by hbm2java
 */
public class JobContractServiceResult  implements java.io.Serializable {

    // Fields    

     private long id;
     private JobContractService jobContractService;
     @NotBlank @Length(min=0, max=105) private String expressionId;
     @NotBlank @Length(min=0, max=105) private String location;
     private Set<Prebill> prebills = new HashSet<Prebill>(0);

     // Constructors

    /** default constructor */
    public JobContractServiceResult() {
    }

	/** minimal constructor */
    public JobContractServiceResult(JobContractService jobContractService) {
        this.jobContractService = jobContractService;
    }
    /** full constructor */
    public JobContractServiceResult(JobContractService jobContractService, String expressionId, String location, Set<Prebill> prebills) {
       this.jobContractService = jobContractService;
       this.expressionId = expressionId;
       this.location = location;
       this.prebills = prebills;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public JobContractService getJobContractService() {
        return this.jobContractService;
    }
    
    public void setJobContractService(JobContractService jobContractService) {
        this.jobContractService = jobContractService;
    }
    public String getExpressionId() {
        return this.expressionId;
    }
    
    public void setExpressionId(String expressionId) {
        this.expressionId = expressionId;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Set<Prebill> getPrebills() {
        return this.prebills;
    }
    
    public void setPrebills(Set<Prebill> prebills) {
        this.prebills = prebills;
    }




}


