package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * JobEventId generated by hbm2java
 */
public class JobEventId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=10) private Integer jobEventId;
     private Integer prodSeqNum;
     @NotBlank @Length(min=0, max=128) private String jobNumber;
     private Integer linkedVslRow;

     // Constructors

    /** default constructor */
    public JobEventId() {
    }

    /** full constructor */
    public JobEventId(Integer jobEventId, Integer prodSeqNum, String jobNumber, Integer linkedVslRow) {
       this.jobEventId = jobEventId;
       this.prodSeqNum = prodSeqNum;
       this.jobNumber = jobNumber;
       this.linkedVslRow = linkedVslRow;
    }
   
    // Property accessors
    public Integer getJobEventId() {
        return this.jobEventId;
    }
    
    public void setJobEventId(Integer jobEventId) {
        this.jobEventId = jobEventId;
    }
    public Integer getProdSeqNum() {
        return this.prodSeqNum;
    }
    
    public void setProdSeqNum(Integer prodSeqNum) {
        this.prodSeqNum = prodSeqNum;
    }
    public String getJobNumber() {
        return this.jobNumber;
    }
    
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }
    public Integer getLinkedVslRow() {
        return this.linkedVslRow;
    }
    
    public void setLinkedVslRow(Integer linkedVslRow) {
        this.linkedVslRow = linkedVslRow;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JobEventId) ) return false;
		 JobEventId castOther = ( JobEventId ) other; 
         
		 return ( (this.getJobEventId()==castOther.getJobEventId()) || ( this.getJobEventId()!=null && castOther.getJobEventId()!=null && this.getJobEventId().equals(castOther.getJobEventId()) ) )
 && ( (this.getProdSeqNum()==castOther.getProdSeqNum()) || ( this.getProdSeqNum()!=null && castOther.getProdSeqNum()!=null && this.getProdSeqNum().equals(castOther.getProdSeqNum()) ) )
 && ( (this.getJobNumber()==castOther.getJobNumber()) || ( this.getJobNumber()!=null && castOther.getJobNumber()!=null && this.getJobNumber().equals(castOther.getJobNumber()) ) )
 && ( (this.getLinkedVslRow()==castOther.getLinkedVslRow()) || ( this.getLinkedVslRow()!=null && castOther.getLinkedVslRow()!=null && this.getLinkedVslRow().equals(castOther.getLinkedVslRow()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getJobEventId() == null ? 0 : this.getJobEventId().hashCode() );
         result = 37 * result + ( getProdSeqNum() == null ? 0 : this.getProdSeqNum().hashCode() );
         result = 37 * result + ( getJobNumber() == null ? 0 : this.getJobNumber().hashCode() );
         result = 37 * result + ( getLinkedVslRow() == null ? 0 : this.getLinkedVslRow().hashCode() );
         return result;
   }   


}


