package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * JobLog generated by hbm2java
 */
public class JobLog  implements java.io.Serializable {

    // Fields    

     private long id;
     @Length(min=0, max=50) private String coordinator;
     @Length(min=0, max=50) private String inspector;
     @Length(min=0, max=4) private String dispatchStatus;
     @Length(min=0, max=6) private String dispatchTz;
     private Date inspectorNotifyDt;
     private Date inspectorNotifyTime;
     private Date inspectorArriveDt;
     private Date inspectorArriveTime;
     private Date arriveDt;
     private Date arriveTime;
     private Date dockDt;
     private Date dockTime;
     private Date hoseOnDt;
     private Date hoseOnTime;
     private Date estStartDt;
     private Date estStartTime;
     private Date commenceDt;
     private Date commenceTime;
     private Date delayDt;
     private Date delayTime;
     private Date delayEndDt;
     private Date delayEndTime;
     private Date estCompleteDt;
     private Date estCompleteTime;
     private Date completeDt;
     private Date completeTime;
     private Date hoseOffDt;
     private Date hoseOffTime;
     private Date releaseDt;
     private Date releaseTime;
     private Date summaryDt;
     @Length(min=0, max=6) private String processTz;
     private Date sampleReceiveDt;
     private Date sampleReceiveTime;
     private Date prelimReportDt;
     private Date prelimReportTime;
     private Date sampleShipDt;
     private Date sampleShipTime;
     private Date finalReportDt;
     private Date finalReportTime;
     private Date distributeDt;
     private Date distributeTime;
     @Length(min=0, max=20) private String uid20;
     private JobOrder jobOrder;
     private JobContract jobContract;

     // Constructors

    /** default constructor */
    public JobLog() {
    }

    /** full constructor */
    public JobLog(String coordinator, String inspector, String dispatchStatus, String dispatchTz, Date inspectorNotifyDt, Date inspectorNotifyTime, Date inspectorArriveDt, Date inspectorArriveTime, Date arriveDt, Date arriveTime, Date dockDt, Date dockTime, Date hoseOnDt, Date hoseOnTime, Date estStartDt, Date estStartTime, Date commenceDt, Date commenceTime, Date delayDt, Date delayTime, Date delayEndDt, Date delayEndTime, Date estCompleteDt, Date estCompleteTime, Date completeDt, Date completeTime, Date hoseOffDt, Date hoseOffTime, Date releaseDt, Date releaseTime, Date summaryDt, String processTz, Date sampleReceiveDt, Date sampleReceiveTime, Date prelimReportDt, Date prelimReportTime, Date sampleShipDt, Date sampleShipTime, Date finalReportDt, Date finalReportTime, Date distributeDt, Date distributeTime, String uid20, JobOrder jobOrder, JobContract jobContract) {
       this.coordinator = coordinator;
       this.inspector = inspector;
       this.dispatchStatus = dispatchStatus;
       this.dispatchTz = dispatchTz;
       this.inspectorNotifyDt = inspectorNotifyDt;
       this.inspectorNotifyTime = inspectorNotifyTime;
       this.inspectorArriveDt = inspectorArriveDt;
       this.inspectorArriveTime = inspectorArriveTime;
       this.arriveDt = arriveDt;
       this.arriveTime = arriveTime;
       this.dockDt = dockDt;
       this.dockTime = dockTime;
       this.hoseOnDt = hoseOnDt;
       this.hoseOnTime = hoseOnTime;
       this.estStartDt = estStartDt;
       this.estStartTime = estStartTime;
       this.commenceDt = commenceDt;
       this.commenceTime = commenceTime;
       this.delayDt = delayDt;
       this.delayTime = delayTime;
       this.delayEndDt = delayEndDt;
       this.delayEndTime = delayEndTime;
       this.estCompleteDt = estCompleteDt;
       this.estCompleteTime = estCompleteTime;
       this.completeDt = completeDt;
       this.completeTime = completeTime;
       this.hoseOffDt = hoseOffDt;
       this.hoseOffTime = hoseOffTime;
       this.releaseDt = releaseDt;
       this.releaseTime = releaseTime;
       this.summaryDt = summaryDt;
       this.processTz = processTz;
       this.sampleReceiveDt = sampleReceiveDt;
       this.sampleReceiveTime = sampleReceiveTime;
       this.prelimReportDt = prelimReportDt;
       this.prelimReportTime = prelimReportTime;
       this.sampleShipDt = sampleShipDt;
       this.sampleShipTime = sampleShipTime;
       this.finalReportDt = finalReportDt;
       this.finalReportTime = finalReportTime;
       this.distributeDt = distributeDt;
       this.distributeTime = distributeTime;
       this.uid20 = uid20;
       this.jobOrder = jobOrder;
       this.jobContract = jobContract;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getCoordinator() {
        return this.coordinator;
    }
    
    public void setCoordinator(String coordinator) {
        this.coordinator = coordinator;
    }
    public String getInspector() {
        return this.inspector;
    }
    
    public void setInspector(String inspector) {
        this.inspector = inspector;
    }
    public String getDispatchStatus() {
        return this.dispatchStatus;
    }
    
    public void setDispatchStatus(String dispatchStatus) {
        this.dispatchStatus = dispatchStatus;
    }
    public String getDispatchTz() {
        return this.dispatchTz;
    }
    
    public void setDispatchTz(String dispatchTz) {
        this.dispatchTz = dispatchTz;
    }
    public Date getInspectorNotifyDt() {
        return this.inspectorNotifyDt;
    }
    
    public void setInspectorNotifyDt(Date inspectorNotifyDt) {
        this.inspectorNotifyDt = inspectorNotifyDt;
    }
    public Date getInspectorNotifyTime() {
        return this.inspectorNotifyTime;
    }
    
    public void setInspectorNotifyTime(Date inspectorNotifyTime) {
        this.inspectorNotifyTime = inspectorNotifyTime;
    }
    public Date getInspectorArriveDt() {
        return this.inspectorArriveDt;
    }
    
    public void setInspectorArriveDt(Date inspectorArriveDt) {
        this.inspectorArriveDt = inspectorArriveDt;
    }
    public Date getInspectorArriveTime() {
        return this.inspectorArriveTime;
    }
    
    public void setInspectorArriveTime(Date inspectorArriveTime) {
        this.inspectorArriveTime = inspectorArriveTime;
    }
    public Date getArriveDt() {
        return this.arriveDt;
    }
    
    public void setArriveDt(Date arriveDt) {
        this.arriveDt = arriveDt;
    }
    public Date getArriveTime() {
        return this.arriveTime;
    }
    
    public void setArriveTime(Date arriveTime) {
        this.arriveTime = arriveTime;
    }
    public Date getDockDt() {
        return this.dockDt;
    }
    
    public void setDockDt(Date dockDt) {
        this.dockDt = dockDt;
    }
    public Date getDockTime() {
        return this.dockTime;
    }
    
    public void setDockTime(Date dockTime) {
        this.dockTime = dockTime;
    }
    public Date getHoseOnDt() {
        return this.hoseOnDt;
    }
    
    public void setHoseOnDt(Date hoseOnDt) {
        this.hoseOnDt = hoseOnDt;
    }
    public Date getHoseOnTime() {
        return this.hoseOnTime;
    }
    
    public void setHoseOnTime(Date hoseOnTime) {
        this.hoseOnTime = hoseOnTime;
    }
    public Date getEstStartDt() {
        return this.estStartDt;
    }
    
    public void setEstStartDt(Date estStartDt) {
        this.estStartDt = estStartDt;
    }
    public Date getEstStartTime() {
        return this.estStartTime;
    }
    
    public void setEstStartTime(Date estStartTime) {
        this.estStartTime = estStartTime;
    }
    public Date getCommenceDt() {
        return this.commenceDt;
    }
    
    public void setCommenceDt(Date commenceDt) {
        this.commenceDt = commenceDt;
    }
    public Date getCommenceTime() {
        return this.commenceTime;
    }
    
    public void setCommenceTime(Date commenceTime) {
        this.commenceTime = commenceTime;
    }
    public Date getDelayDt() {
        return this.delayDt;
    }
    
    public void setDelayDt(Date delayDt) {
        this.delayDt = delayDt;
    }
    public Date getDelayTime() {
        return this.delayTime;
    }
    
    public void setDelayTime(Date delayTime) {
        this.delayTime = delayTime;
    }
    public Date getDelayEndDt() {
        return this.delayEndDt;
    }
    
    public void setDelayEndDt(Date delayEndDt) {
        this.delayEndDt = delayEndDt;
    }
    public Date getDelayEndTime() {
        return this.delayEndTime;
    }
    
    public void setDelayEndTime(Date delayEndTime) {
        this.delayEndTime = delayEndTime;
    }
    public Date getEstCompleteDt() {
        return this.estCompleteDt;
    }
    
    public void setEstCompleteDt(Date estCompleteDt) {
        this.estCompleteDt = estCompleteDt;
    }
    public Date getEstCompleteTime() {
        return this.estCompleteTime;
    }
    
    public void setEstCompleteTime(Date estCompleteTime) {
        this.estCompleteTime = estCompleteTime;
    }
    public Date getCompleteDt() {
        return this.completeDt;
    }
    
    public void setCompleteDt(Date completeDt) {
        this.completeDt = completeDt;
    }
    public Date getCompleteTime() {
        return this.completeTime;
    }
    
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }
    public Date getHoseOffDt() {
        return this.hoseOffDt;
    }
    
    public void setHoseOffDt(Date hoseOffDt) {
        this.hoseOffDt = hoseOffDt;
    }
    public Date getHoseOffTime() {
        return this.hoseOffTime;
    }
    
    public void setHoseOffTime(Date hoseOffTime) {
        this.hoseOffTime = hoseOffTime;
    }
    public Date getReleaseDt() {
        return this.releaseDt;
    }
    
    public void setReleaseDt(Date releaseDt) {
        this.releaseDt = releaseDt;
    }
    public Date getReleaseTime() {
        return this.releaseTime;
    }
    
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }
    public Date getSummaryDt() {
        return this.summaryDt;
    }
    
    public void setSummaryDt(Date summaryDt) {
        this.summaryDt = summaryDt;
    }
    public String getProcessTz() {
        return this.processTz;
    }
    
    public void setProcessTz(String processTz) {
        this.processTz = processTz;
    }
    public Date getSampleReceiveDt() {
        return this.sampleReceiveDt;
    }
    
    public void setSampleReceiveDt(Date sampleReceiveDt) {
        this.sampleReceiveDt = sampleReceiveDt;
    }
    public Date getSampleReceiveTime() {
        return this.sampleReceiveTime;
    }
    
    public void setSampleReceiveTime(Date sampleReceiveTime) {
        this.sampleReceiveTime = sampleReceiveTime;
    }
    public Date getPrelimReportDt() {
        return this.prelimReportDt;
    }
    
    public void setPrelimReportDt(Date prelimReportDt) {
        this.prelimReportDt = prelimReportDt;
    }
    public Date getPrelimReportTime() {
        return this.prelimReportTime;
    }
    
    public void setPrelimReportTime(Date prelimReportTime) {
        this.prelimReportTime = prelimReportTime;
    }
    public Date getSampleShipDt() {
        return this.sampleShipDt;
    }
    
    public void setSampleShipDt(Date sampleShipDt) {
        this.sampleShipDt = sampleShipDt;
    }
    public Date getSampleShipTime() {
        return this.sampleShipTime;
    }
    
    public void setSampleShipTime(Date sampleShipTime) {
        this.sampleShipTime = sampleShipTime;
    }
    public Date getFinalReportDt() {
        return this.finalReportDt;
    }
    
    public void setFinalReportDt(Date finalReportDt) {
        this.finalReportDt = finalReportDt;
    }
    public Date getFinalReportTime() {
        return this.finalReportTime;
    }
    
    public void setFinalReportTime(Date finalReportTime) {
        this.finalReportTime = finalReportTime;
    }
    public Date getDistributeDt() {
        return this.distributeDt;
    }
    
    public void setDistributeDt(Date distributeDt) {
        this.distributeDt = distributeDt;
    }
    public Date getDistributeTime() {
        return this.distributeTime;
    }
    
    public void setDistributeTime(Date distributeTime) {
        this.distributeTime = distributeTime;
    }
    public String getUid20() {
        return this.uid20;
    }
    
    public void setUid20(String uid20) {
        this.uid20 = uid20;
    }
    public JobOrder getJobOrder() {
        return this.jobOrder;
    }
    
    public void setJobOrder(JobOrder jobOrder) {
        this.jobOrder = jobOrder;
    }
    public JobContract getJobContract() {
        return this.jobContract;
    }
    
    public void setJobContract(JobContract jobContract) {
        this.jobContract = jobContract;
    }




}


