package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * JobVesselId generated by hbm2java
 */
public class JobVesselId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=128) private String jobNumber;
     private Integer linkedVslRow;

     // Constructors

    /** default constructor */
    public JobVesselId() {
    }

    /** full constructor */
    public JobVesselId(String jobNumber, Integer linkedVslRow) {
       this.jobNumber = jobNumber;
       this.linkedVslRow = linkedVslRow;
    }
   
    // Property accessors
    public String getJobNumber() {
        return this.jobNumber;
    }
    
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }
    public Integer getLinkedVslRow() {
        return this.linkedVslRow;
    }
    
    public void setLinkedVslRow(Integer linkedVslRow) {
        this.linkedVslRow = linkedVslRow;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JobVesselId) ) return false;
		 JobVesselId castOther = ( JobVesselId ) other; 
         
		 return ( (this.getJobNumber()==castOther.getJobNumber()) || ( this.getJobNumber()!=null && castOther.getJobNumber()!=null && this.getJobNumber().equals(castOther.getJobNumber()) ) )
 && ( (this.getLinkedVslRow()==castOther.getLinkedVslRow()) || ( this.getLinkedVslRow()!=null && castOther.getLinkedVslRow()!=null && this.getLinkedVslRow().equals(castOther.getLinkedVslRow()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getJobNumber() == null ? 0 : this.getJobNumber().hashCode() );
         result = 37 * result + ( getLinkedVslRow() == null ? 0 : this.getLinkedVslRow().hashCode() );
         return result;
   }   


}


