package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * JobVessel generated by hbm2java
 */
public class JobVessel  implements java.io.Serializable {

    // Fields    

     private JobVesselId jobVesselId;
     private JobOrder jobOrder;
     @NotBlank @Length(min=0, max=256) private String vesselName;
     @Length(min=0, max=16) private String type;
     private Set<JobProd> jobProds = new HashSet<JobProd>(0);

     // Constructors

    /** default constructor */
    public JobVessel() {
    }

	/** minimal constructor */
    public JobVessel(JobVesselId jobVesselId, String vesselName) {
        this.jobVesselId = jobVesselId;
        this.vesselName = vesselName;
    }
    /** full constructor */
    public JobVessel(JobVesselId jobVesselId, JobOrder jobOrder, String vesselName, String type, Set<JobProd> jobProds) {
       this.jobVesselId = jobVesselId;
       this.jobOrder = jobOrder;
       this.vesselName = vesselName;
       this.type = type;
       this.jobProds = jobProds;
    }
   
    // Property accessors
    public JobVesselId getJobVesselId() {
        return this.jobVesselId;
    }
    
    public void setJobVesselId(JobVesselId jobVesselId) {
        this.jobVesselId = jobVesselId;
    }
    public JobOrder getJobOrder() {
        return this.jobOrder;
    }
    
    public void setJobOrder(JobOrder jobOrder) {
        this.jobOrder = jobOrder;
    }
    public String getVesselName() {
        return this.vesselName;
    }
    
    public void setVesselName(String vesselName) {
        this.vesselName = vesselName;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set<JobProd> getJobProds() {
        return this.jobProds;
    }
    
    public void setJobProds(Set<JobProd> jobProds) {
        this.jobProds = jobProds;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JobVessel) ) return false;
		 JobVessel castOther = ( JobVessel ) other; 
         
		 return ( (this.getJobVesselId()==castOther.getJobVesselId()) || ( this.getJobVesselId()!=null && castOther.getJobVesselId()!=null && this.getJobVesselId().equals(castOther.getJobVesselId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getJobVesselId() == null ? 0 : this.getJobVesselId().hashCode() );
         
         
         
         
         return result;
   }   


}


