package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * LabCapability generated by hbm2java
 */
public class LabCapability  implements java.io.Serializable {

    // Fields    

     private LabCapabilityId labCapabilityId;
     @Length(min=0, max=762) private String capabilityRemarks;

     // Constructors

    /** default constructor */
    public LabCapability() {
    }

	/** minimal constructor */
    public LabCapability(LabCapabilityId labCapabilityId) {
        this.labCapabilityId = labCapabilityId;
    }
    /** full constructor */
    public LabCapability(LabCapabilityId labCapabilityId, String capabilityRemarks) {
       this.labCapabilityId = labCapabilityId;
       this.capabilityRemarks = capabilityRemarks;
    }
   
    // Property accessors
    public LabCapabilityId getLabCapabilityId() {
        return this.labCapabilityId;
    }
    
    public void setLabCapabilityId(LabCapabilityId labCapabilityId) {
        this.labCapabilityId = labCapabilityId;
    }
    public String getCapabilityRemarks() {
        return this.capabilityRemarks;
    }
    
    public void setCapabilityRemarks(String capabilityRemarks) {
        this.capabilityRemarks = capabilityRemarks;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LabCapability) ) return false;
		 LabCapability castOther = ( LabCapability ) other; 
         
		 return ( (this.getLabCapabilityId()==castOther.getLabCapabilityId()) || ( this.getLabCapabilityId()!=null && castOther.getLabCapabilityId()!=null && this.getLabCapabilityId().equals(castOther.getLabCapabilityId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLabCapabilityId() == null ? 0 : this.getLabCapabilityId().hashCode() );
         
         return result;
   }   


}


