package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * PortLocation generated by hbm2java
 */
public class PortLocation  implements java.io.Serializable {

    // Fields    

     private PortLocationId portLocationId;
     private Date endDate;

     // Constructors

    /** default constructor */
    public PortLocation() {
    }

	/** minimal constructor */
    public PortLocation(PortLocationId portLocationId) {
        this.portLocationId = portLocationId;
    }
    /** full constructor */
    public PortLocation(PortLocationId portLocationId, Date endDate) {
       this.portLocationId = portLocationId;
       this.endDate = endDate;
    }
   
    // Property accessors
    public PortLocationId getPortLocationId() {
        return this.portLocationId;
    }
    
    public void setPortLocationId(PortLocationId portLocationId) {
        this.portLocationId = portLocationId;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PortLocation) ) return false;
		 PortLocation castOther = ( PortLocation ) other; 
         
		 return ( (this.getPortLocationId()==castOther.getPortLocationId()) || ( this.getPortLocationId()!=null && castOther.getPortLocationId()!=null && this.getPortLocationId().equals(castOther.getPortLocationId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPortLocationId() == null ? 0 : this.getPortLocationId().hashCode() );
         
         return result;
   }   


}


