package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * PriceBook generated by hbm2java
 */
public class PriceBook  implements java.io.Serializable {

    // Fields    

     private PriceBookId priceBookId;
     private Date endDate;

     // Constructors

    /** default constructor */
    public PriceBook() {
    }

	/** minimal constructor */
    public PriceBook(PriceBookId priceBookId) {
        this.priceBookId = priceBookId;
    }
    /** full constructor */
    public PriceBook(PriceBookId priceBookId, Date endDate) {
       this.priceBookId = priceBookId;
       this.endDate = endDate;
    }
   
    // Property accessors
    public PriceBookId getPriceBookId() {
        return this.priceBookId;
    }
    
    public void setPriceBookId(PriceBookId priceBookId) {
        this.priceBookId = priceBookId;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PriceBook) ) return false;
		 PriceBook castOther = ( PriceBook ) other; 
         
		 return ( (this.getPriceBookId()==castOther.getPriceBookId()) || ( this.getPriceBookId()!=null && castOther.getPriceBookId()!=null && this.getPriceBookId().equals(castOther.getPriceBookId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPriceBookId() == null ? 0 : this.getPriceBookId().hashCode() );
         
         return result;
   }   


}


