package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * PriceBookTestModId generated by hbm2java
 */
public class PriceBookTestModId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=45) private String contractId;
     @NotBlank @Length(min=0, max=3) private String testType;
     @NotBlank @Length(min=0, max=96) private String testId;

     // Constructors

    /** default constructor */
    public PriceBookTestModId() {
    }

    /** full constructor */
    public PriceBookTestModId(String contractId, String testType, String testId) {
       this.contractId = contractId;
       this.testType = testType;
       this.testId = testId;
    }
   
    // Property accessors
    public String getContractId() {
        return this.contractId;
    }
    
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }
    public String getTestType() {
        return this.testType;
    }
    
    public void setTestType(String testType) {
        this.testType = testType;
    }
    public String getTestId() {
        return this.testId;
    }
    
    public void setTestId(String testId) {
        this.testId = testId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PriceBookTestModId) ) return false;
		 PriceBookTestModId castOther = ( PriceBookTestModId ) other; 
         
		 return ( (this.getContractId()==castOther.getContractId()) || ( this.getContractId()!=null && castOther.getContractId()!=null && this.getContractId().equals(castOther.getContractId()) ) )
 && ( (this.getTestType()==castOther.getTestType()) || ( this.getTestType()!=null && castOther.getTestType()!=null && this.getTestType().equals(castOther.getTestType()) ) )
 && ( (this.getTestId()==castOther.getTestId()) || ( this.getTestId()!=null && castOther.getTestId()!=null && this.getTestId().equals(castOther.getTestId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getContractId() == null ? 0 : this.getContractId().hashCode() );
         result = 37 * result + ( getTestType() == null ? 0 : this.getTestType().hashCode() );
         result = 37 * result + ( getTestId() == null ? 0 : this.getTestId().hashCode() );
         return result;
   }   


}


