package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * PriceBookId generated by hbm2java
 */
public class PriceBookId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=45) private String priceBookId;
     @NotBlank @Length(min=0, max=9) private String currencyCD;
     @NotBlank @Length(min=0, max=45) private String pbSeries;
     private Date beginDate;

     // Constructors

    /** default constructor */
    public PriceBookId() {
    }

    /** full constructor */
    public PriceBookId(String priceBookId, String currencyCD, String pbSeries, Date beginDate) {
       this.priceBookId = priceBookId;
       this.currencyCD = currencyCD;
       this.pbSeries = pbSeries;
       this.beginDate = beginDate;
    }
   
    // Property accessors
    public String getPriceBookId() {
        return this.priceBookId;
    }
    
    public void setPriceBookId(String priceBookId) {
        this.priceBookId = priceBookId;
    }
    public String getCurrencyCD() {
        return this.currencyCD;
    }
    
    public void setCurrencyCD(String currencyCD) {
        this.currencyCD = currencyCD;
    }
    public String getPbSeries() {
        return this.pbSeries;
    }
    
    public void setPbSeries(String pbSeries) {
        this.pbSeries = pbSeries;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PriceBookId) ) return false;
		 PriceBookId castOther = ( PriceBookId ) other; 
         
		 return ( (this.getPriceBookId()==castOther.getPriceBookId()) || ( this.getPriceBookId()!=null && castOther.getPriceBookId()!=null && this.getPriceBookId().equals(castOther.getPriceBookId()) ) )
 && ( (this.getCurrencyCD()==castOther.getCurrencyCD()) || ( this.getCurrencyCD()!=null && castOther.getCurrencyCD()!=null && this.getCurrencyCD().equals(castOther.getCurrencyCD()) ) )
 && ( (this.getPbSeries()==castOther.getPbSeries()) || ( this.getPbSeries()!=null && castOther.getPbSeries()!=null && this.getPbSeries().equals(castOther.getPbSeries()) ) )
 && ( (this.getBeginDate()==castOther.getBeginDate()) || ( this.getBeginDate()!=null && castOther.getBeginDate()!=null && this.getBeginDate().equals(castOther.getBeginDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPriceBookId() == null ? 0 : this.getPriceBookId().hashCode() );
         result = 37 * result + ( getCurrencyCD() == null ? 0 : this.getCurrencyCD().hashCode() );
         result = 37 * result + ( getPbSeries() == null ? 0 : this.getPbSeries().hashCode() );
         result = 37 * result + ( getBeginDate() == null ? 0 : this.getBeginDate().hashCode() );
         return result;
   }   


}


