package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * RateMap generated by hbm2java
 */
public class RateMap  implements java.io.Serializable {

    // Fields    

     private RateMapId rateMapId;
     @NotBlank @Length(min=0, max=3) private String withInspection;
     @NotBlank @Length(min=0, max=12) private String serviceLevel;

     // Constructors

    /** default constructor */
    public RateMap() {
    }

    /** full constructor */
    public RateMap(RateMapId rateMapId, String withInspection, String serviceLevel) {
       this.rateMapId = rateMapId;
       this.withInspection = withInspection;
       this.serviceLevel = serviceLevel;
    }
   
    // Property accessors
    public RateMapId getRateMapId() {
        return this.rateMapId;
    }
    
    public void setRateMapId(RateMapId rateMapId) {
        this.rateMapId = rateMapId;
    }
    public String getWithInspection() {
        return this.withInspection;
    }
    
    public void setWithInspection(String withInspection) {
        this.withInspection = withInspection;
    }
    public String getServiceLevel() {
        return this.serviceLevel;
    }
    
    public void setServiceLevel(String serviceLevel) {
        this.serviceLevel = serviceLevel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RateMap) ) return false;
		 RateMap castOther = ( RateMap ) other; 
         
		 return ( (this.getRateMapId()==castOther.getRateMapId()) || ( this.getRateMapId()!=null && castOther.getRateMapId()!=null && this.getRateMapId().equals(castOther.getRateMapId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRateMapId() == null ? 0 : this.getRateMapId().hashCode() );
         
         
         return result;
   }   


}


