package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ReferenceFieldId generated by hbm2java
 */
public class ReferenceFieldId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=45) private String contractId;
     @NotBlank @Length(min=0, max=45) private String referenceFieldId;

     // Constructors

    /** default constructor */
    public ReferenceFieldId() {
    }

    /** full constructor */
    public ReferenceFieldId(String contractId, String referenceFieldId) {
       this.contractId = contractId;
       this.referenceFieldId = referenceFieldId;
    }
   
    // Property accessors
    public String getContractId() {
        return this.contractId;
    }
    
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }
    public String getReferenceFieldId() {
        return this.referenceFieldId;
    }
    
    public void setReferenceFieldId(String referenceFieldId) {
        this.referenceFieldId = referenceFieldId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReferenceFieldId) ) return false;
		 ReferenceFieldId castOther = ( ReferenceFieldId ) other; 
         
		 return ( (this.getContractId()==castOther.getContractId()) || ( this.getContractId()!=null && castOther.getContractId()!=null && this.getContractId().equals(castOther.getContractId()) ) )
 && ( (this.getReferenceFieldId()==castOther.getReferenceFieldId()) || ( this.getReferenceFieldId()!=null && castOther.getReferenceFieldId()!=null && this.getReferenceFieldId().equals(castOther.getReferenceFieldId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getContractId() == null ? 0 : this.getContractId().hashCode() );
         result = 37 * result + ( getReferenceFieldId() == null ? 0 : this.getReferenceFieldId().hashCode() );
         return result;
   }   


}


