package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * RequiredField generated by hbm2java
 */
public class RequiredField  implements java.io.Serializable {

    // Fields    

     private RequiredFieldId requiredFieldId;
     private Boolean multiInst;
     private Boolean mask;
     private Boolean insp;
     private Boolean mar;
     private Boolean fst;
     private Boolean out;
     @Length(min=0, max=762) private String remark;

     // Constructors

    /** default constructor */
    public RequiredField() {
    }

	/** minimal constructor */
    public RequiredField(RequiredFieldId requiredFieldId) {
        this.requiredFieldId = requiredFieldId;
    }
    /** full constructor */
    public RequiredField(RequiredFieldId requiredFieldId, Boolean multiInst, Boolean mask, Boolean insp, Boolean mar, Boolean fst, Boolean out, String remark) {
       this.requiredFieldId = requiredFieldId;
       this.multiInst = multiInst;
       this.mask = mask;
       this.insp = insp;
       this.mar = mar;
       this.fst = fst;
       this.out = out;
       this.remark = remark;
    }
   
    // Property accessors
    public RequiredFieldId getRequiredFieldId() {
        return this.requiredFieldId;
    }
    
    public void setRequiredFieldId(RequiredFieldId requiredFieldId) {
        this.requiredFieldId = requiredFieldId;
    }
    public Boolean getMultiInst() {
        return this.multiInst;
    }
    
    public void setMultiInst(Boolean multiInst) {
        this.multiInst = multiInst;
    }
    public Boolean getMask() {
        return this.mask;
    }
    
    public void setMask(Boolean mask) {
        this.mask = mask;
    }
    public Boolean getInsp() {
        return this.insp;
    }
    
    public void setInsp(Boolean insp) {
        this.insp = insp;
    }
    public Boolean getMar() {
        return this.mar;
    }
    
    public void setMar(Boolean mar) {
        this.mar = mar;
    }
    public Boolean getFst() {
        return this.fst;
    }
    
    public void setFst(Boolean fst) {
        this.fst = fst;
    }
    public Boolean getOut() {
        return this.out;
    }
    
    public void setOut(Boolean out) {
        this.out = out;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RequiredField) ) return false;
		 RequiredField castOther = ( RequiredField ) other; 
         
		 return ( (this.getRequiredFieldId()==castOther.getRequiredFieldId()) || ( this.getRequiredFieldId()!=null && castOther.getRequiredFieldId()!=null && this.getRequiredFieldId().equals(castOther.getRequiredFieldId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRequiredFieldId() == null ? 0 : this.getRequiredFieldId().hashCode() );
         
         
         
         
         
         
         
         return result;
   }   


}


