package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ServiceId generated by hbm2java
 */
public class ServiceId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=45) private String contractId;
     @NotBlank @Length(min=0, max=60) private String serviceName;
     @NotBlank @Length(min=0, max=96) private String parentServiceId;
     private Date beginDate;

     // Constructors

    /** default constructor */
    public ServiceId() {
    }

    /** full constructor */
    public ServiceId(String contractId, String serviceName, String parentServiceId, Date beginDate) {
       this.contractId = contractId;
       this.serviceName = serviceName;
       this.parentServiceId = parentServiceId;
       this.beginDate = beginDate;
    }
   
    // Property accessors
    public String getContractId() {
        return this.contractId;
    }
    
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }
    public String getParentServiceId() {
        return this.parentServiceId;
    }
    
    public void setParentServiceId(String parentServiceId) {
        this.parentServiceId = parentServiceId;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ServiceId) ) return false;
		 ServiceId castOther = ( ServiceId ) other; 
         
		 return ( (this.getContractId()==castOther.getContractId()) || ( this.getContractId()!=null && castOther.getContractId()!=null && this.getContractId().equals(castOther.getContractId()) ) )
 && ( (this.getServiceName()==castOther.getServiceName()) || ( this.getServiceName()!=null && castOther.getServiceName()!=null && this.getServiceName().equals(castOther.getServiceName()) ) )
 && ( (this.getParentServiceId()==castOther.getParentServiceId()) || ( this.getParentServiceId()!=null && castOther.getParentServiceId()!=null && this.getParentServiceId().equals(castOther.getParentServiceId()) ) )
 && ( (this.getBeginDate()==castOther.getBeginDate()) || ( this.getBeginDate()!=null && castOther.getBeginDate()!=null && this.getBeginDate().equals(castOther.getBeginDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getContractId() == null ? 0 : this.getContractId().hashCode() );
         result = 37 * result + ( getServiceName() == null ? 0 : this.getServiceName().hashCode() );
         result = 37 * result + ( getParentServiceId() == null ? 0 : this.getParentServiceId().hashCode() );
         result = 37 * result + ( getBeginDate() == null ? 0 : this.getBeginDate().hashCode() );
         return result;
   }   


}


