package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ServiceRate generated by hbm2java
 */
public class ServiceRate  implements java.io.Serializable {

    // Fields    

     private ServiceRateId serviceRateId;
     private Integer rateId;
     @Length(min=0, max=9) private String currencyCD;
     private Double basePrice;
     private Double unitPrice;
     private Double minimumPrice;
     private Double maximumPrice;
     private Double unitsIncluded;
     private Integer intData0;
     private Integer intData1;
     private Long intData3;
     private Integer intData4;
     private Double floatData0;
     private Double floatData1;
     private Double floatData3;
     private Double floatData4;
     @Length(min=0, max=45) private String contractRef;
     private Date endDate;

     // Constructors

    /** default constructor */
    public ServiceRate() {
    }

	/** minimal constructor */
    public ServiceRate(ServiceRateId serviceRateId) {
        this.serviceRateId = serviceRateId;
    }
    
    /** full constructor */
    public ServiceRate(ServiceRateId serviceRateId, Integer rateId, String currencyCD, Double basePrice, Double unitPrice, Double minimumPrice, Double maximumPrice, Double unitsIncluded, Integer intData0, Integer intData1, Long intData3, Integer intData4, Double floatData0, Double floatData1, Double floatData3, Double floatData4, String contractRef, Date endDate) {
       this.serviceRateId = serviceRateId;
       this.rateId = rateId;
       this.currencyCD = currencyCD;
       this.basePrice = basePrice;
       this.unitPrice = unitPrice;
       this.minimumPrice = minimumPrice;
       this.maximumPrice = maximumPrice;
       this.unitsIncluded = unitsIncluded;
       this.intData0 = intData0;
       this.intData1 = intData1;
       this.intData3 = intData3;
       this.intData4 = intData4;
       this.floatData0 = floatData0;
       this.floatData1 = floatData1;
       this.floatData3 = floatData3;
       this.floatData4 = floatData4;
       this.contractRef = contractRef;
       this.endDate = endDate;
    }
    
    public ServiceRate(ServiceRate original){
       this.serviceRateId = original.serviceRateId;
       this.rateId = original.rateId;
       this.currencyCD = original.currencyCD;
       this.basePrice = original.basePrice;
       this.unitPrice = original.unitPrice;
       this.minimumPrice = original.minimumPrice;
       this.maximumPrice = original.maximumPrice;
       this.unitsIncluded = original.unitsIncluded;
       this.intData0 = original.intData0;
       this.intData1 = original.intData1;
       this.intData3 = original.intData3;
       this.intData4 = original.intData4;
       this.floatData0 = original.floatData0;
       this.floatData1 = original.floatData1;
       this.floatData3 = original.floatData3;
       this.floatData4 = original.floatData4;
       this.contractRef = original.contractRef;
       this.endDate = original.endDate;
    }
   
    // Property accessors
    public ServiceRateId getServiceRateId() {
        return this.serviceRateId;
    }
    
    public void setServiceRateId(ServiceRateId serviceRateId) {
        this.serviceRateId = serviceRateId;
    }
    public Integer getRateId() {
        return this.rateId;
    }
    
    public void setRateId(Integer rateId) {
        this.rateId = rateId;
    }
    public String getCurrencyCD() {
        return this.currencyCD;
    }
    
    public void setCurrencyCD(String currencyCD) {
        this.currencyCD = currencyCD;
    }
    public Double getBasePrice() {
        return this.basePrice;
    }
    
    public void setBasePrice(Double basePrice) {
        this.basePrice = basePrice;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Double getMinimumPrice() {
        return this.minimumPrice;
    }
    
    public void setMinimumPrice(Double minimumPrice) {
        this.minimumPrice = minimumPrice;
    }
    public Double getMaximumPrice() {
        return this.maximumPrice;
    }
    
    public void setMaximumPrice(Double maximumPrice) {
        this.maximumPrice = maximumPrice;
    }
    public Double getUnitsIncluded() {
        return this.unitsIncluded;
    }
    
    public void setUnitsIncluded(Double unitsIncluded) {
        this.unitsIncluded = unitsIncluded;
    }
    public Integer getIntData0() {
        return this.intData0;
    }
    
    public void setIntData0(Integer intData0) {
        this.intData0 = intData0;
    }
    public Integer getIntData1() {
        return this.intData1;
    }
    
    public void setIntData1(Integer intData1) {
        this.intData1 = intData1;
    }
    public Long getIntData3() {
        return this.intData3;
    }
    
    public void setIntData3(Long intData3) {
        this.intData3 = intData3;
    }
    public Integer getIntData4() {
        return this.intData4;
    }
    
    public void setIntData4(Integer intData4) {
        this.intData4 = intData4;
    }
    public Double getFloatData0() {
        return this.floatData0;
    }
    
    public void setFloatData0(Double floatData0) {
        this.floatData0 = floatData0;
    }
    public Double getFloatData1() {
        return this.floatData1;
    }
    
    public void setFloatData1(Double floatData1) {
        this.floatData1 = floatData1;
    }
    public Double getFloatData3() {
        return this.floatData3;
    }
    
    public void setFloatData3(Double floatData3) {
        this.floatData3 = floatData3;
    }
    public Double getFloatData4() {
        return this.floatData4;
    }
    
    public void setFloatData4(Double floatData4) {
        this.floatData4 = floatData4;
    }
    public String getContractRef() {
        return this.contractRef;
    }
    
    public void setContractRef(String contractRef) {
        this.contractRef = contractRef;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ServiceRate) ) return false;
		 ServiceRate castOther = ( ServiceRate ) other; 
         
		 return ( (this.getServiceRateId()==castOther.getServiceRateId()) || ( this.getServiceRateId()!=null && castOther.getServiceRateId()!=null && this.getServiceRateId().equals(castOther.getServiceRateId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getServiceRateId() == null ? 0 : this.getServiceRateId().hashCode() );
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         return result;
   }   


}


