package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

import com.intertek.phoenix.util.CommonUtil;
import com.intertek.util.StringUtil;

/**
 * ServiceLocation generated by hbm2java
 */
@Entity
public class ServiceLocation  implements java.io.Serializable {

    // Fields    
	 @Id
     @NotBlank @Length(min=0, max=15) private String serviceLocationCode;
     @Length(min=0, max=254) private String name;
     @Length(min=0, max=1) private String status;
     @Length(min=0, max=55) private String address1;
     @Length(min=0, max=55) private String address2;
     @Length(min=0, max=55) private String address3;
     @Length(min=0, max=55) private String address4;
     @Length(min=0, max=30) private String city;
     @Length(min=0, max=6) private String num1;
     @Length(min=0, max=4) private String num2;
     @Length(min=0, max=2) private String houseType;
     @Length(min=0, max=2) private String addrField1;
     @Length(min=0, max=4) private String addrField2;
     @Length(min=0, max=4) private String addrField3;
     @Length(min=0, max=12) private String postal;
     @Email @Length(min=0, max=70) private String email;
     @Length(min=0, max=32) private String phone;
     @Length(min=0, max=6) private String stateCode;
     @NotBlank @Length(min=0, max=3) private String countryCode;
     private Country country;
     private State state;
     @Length(min=0, max=8) private String branchName;
     
     @ManyToOne
     @JoinColumn(name="BRANCH_NAME")
     private Branch branch;
     
     @ManyToOne
     @JoinColumn(name="BRANCH_NAME")
     private Customer shipToCustomer;
     @Length(min=0, max=15) private String custCode;
     private Integer locationNumber;
     private CustAddrSeq shipToCustAddress;

     // Constructors

    /** default constructor */
    public ServiceLocation() {
    }

	/** minimal constructor */
    public ServiceLocation(String serviceLocationCode, String countryCode) {
        this.serviceLocationCode = serviceLocationCode;
        this.countryCode = countryCode;
    }
    /** full constructor */
    public ServiceLocation(String serviceLocationCode, String name, String status, String address1, String address2, String address3, String address4, String city, String num1, String num2, String houseType, String addrField1, String addrField2, String addrField3, String postal, String email, String phone, String stateCode, String countryCode, Country country, State state, String branchName, Branch branch, Customer shipToCustomer, String custCode, Integer locationNumber, CustAddrSeq shipToCustAddress) {
       this.serviceLocationCode = serviceLocationCode;
       this.name = name;
       this.status = status;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.address4 = address4;
       this.city = city;
       this.num1 = num1;
       this.num2 = num2;
       this.houseType = houseType;
       this.addrField1 = addrField1;
       this.addrField2 = addrField2;
       this.addrField3 = addrField3;
       this.postal = postal;
       this.email = email;
       this.phone = phone;
       this.stateCode = stateCode;
       this.countryCode = countryCode;
       this.country = country;
       this.state = state;
       this.branchName = branchName;
       this.branch = branch;
       this.shipToCustomer = shipToCustomer;
       this.custCode = custCode;
       this.locationNumber = locationNumber;
       this.shipToCustAddress = shipToCustAddress;
    }
   
    // Property accessors
    public String getServiceLocationCode() {
        return this.serviceLocationCode;
    }
    
    public void setServiceLocationCode(String serviceLocationCode) {
        this.serviceLocationCode = serviceLocationCode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }
    public String getAddress4() {
        return this.address4;
    }
    
    public void setAddress4(String address4) {
        this.address4 = address4;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getNum1() {
        return this.num1;
    }
    
    public void setNum1(String num1) {
        this.num1 = num1;
    }
    public String getNum2() {
        return this.num2;
    }
    
    public void setNum2(String num2) {
        this.num2 = num2;
    }
    public String getHouseType() {
        return this.houseType;
    }
    
    public void setHouseType(String houseType) {
        this.houseType = houseType;
    }
    public String getAddrField1() {
        return this.addrField1;
    }
    
    public void setAddrField1(String addrField1) {
        this.addrField1 = addrField1;
    }
    public String getAddrField2() {
        return this.addrField2;
    }
    
    public void setAddrField2(String addrField2) {
        this.addrField2 = addrField2;
    }
    public String getAddrField3() {
        return this.addrField3;
    }
    
    public void setAddrField3(String addrField3) {
        this.addrField3 = addrField3;
    }
    public String getPostal() {
        return this.postal;
    }
    
    public void setPostal(String postal) {
        this.postal = postal;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getStateCode() {
        return this.stateCode;
    }
    
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public State getState() {
        return this.state;
    }
    
    public void setState(State state) {
        this.state = state;
    }
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public Customer getShipToCustomer() {
        return this.shipToCustomer;
    }
    
    public void setShipToCustomer(Customer shipToCustomer) {
        this.shipToCustomer = shipToCustomer;
    }
    public String getCustCode() {
        return this.custCode;
    }
    
    public void setCustCode(String custCode) {
        this.custCode = custCode;
    }
    public Integer getLocationNumber() {
        return this.locationNumber;
    }
    
    public void setLocationNumber(Integer locationNumber) {
        this.locationNumber = locationNumber;
    }
    public CustAddrSeq getShipToCustAddress() {
        return this.shipToCustAddress;
    }
    
    public void setShipToCustAddress(CustAddrSeq shipToCustAddress) {
        this.shipToCustAddress = shipToCustAddress;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ServiceLocation) ) return false;
		 ServiceLocation castOther = ( ServiceLocation ) other; 
         
		 return ( (this.getServiceLocationCode()==castOther.getServiceLocationCode()) || ( this.getServiceLocationCode()!=null && castOther.getServiceLocationCode()!=null && this.getServiceLocationCode().equals(castOther.getServiceLocationCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getServiceLocationCode() == null ? 0 : this.getServiceLocationCode().hashCode() );
         
         return result;
   }   

   public String getFullAddress() {
       return getFullAddress(",");
   }
   

   /**
    * Get full textual presentation of the address, separate each component
    * with a delimiter
    * 
    * @param delimiter
    *            String used to separate address components
    * @return A full address
    */
   public String getFullAddress(String delimiter) {
       String retVal = "";
       retVal = address1 !=null ? address1 : "" ;
       retVal = appendValue(delimiter, retVal, address2);
       retVal = appendValue(delimiter, retVal, address3);
       retVal = appendValue(delimiter, retVal,  address4);
       retVal = appendValue(delimiter, retVal,  city);
       retVal = appendValue(delimiter, retVal,  stateCode);
       retVal = appendValue(delimiter, retVal,   postal);
       retVal = appendValue(delimiter, retVal,   countryCode);
       return retVal;
   }

   private String appendValue(String delimiter, String retVal, String value) {
       if (value != null && !value.trim().equals("")){
           retVal += (retVal.length() > 0 ? delimiter : "") + value;
       }
       return retVal;
   }

   public String getValue(){
       return (CommonUtil.isNullOrEmpty(this.getName()) ? "" : StringUtil.forHTML(this.getName()) + ",")
            + (CommonUtil.isNullOrEmpty(this.getCity()) ? "" : this.getCity() + ",")
            + (CommonUtil.isNullOrEmpty(this.getStateCode()) ?  "" : this.getState() == null ? "" 
              : CommonUtil.isNullOrEmpty(this.getState().getName()) ? "" : this.getState().getName() + ",")
            + (this.getCountry() == null ? "" : CommonUtil.isNullOrEmpty(this.getCountry().getName()) ? "" : this.getCountry().getName());
    }

}


