package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ServiceVersionId generated by hbm2java
 */
public class ServiceVersionId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=45) private String contractId;
     @NotBlank @Length(min=0, max=375) private String serviceName;
     @NotBlank @Length(min=0, max=105) private String expressionId;
     private Date beginDate;

     // Constructors

    /** default constructor */
    public ServiceVersionId() {
    }

    /** full constructor */
    public ServiceVersionId(String contractId, String serviceName, String expressionId, Date beginDate) {
       this.contractId = contractId;
       this.serviceName = serviceName;
       this.expressionId = expressionId;
       this.beginDate = beginDate;
    }
   
    // Property accessors
    public String getContractId() {
        return this.contractId;
    }
    
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }
    public String getExpressionId() {
        return this.expressionId;
    }
    
    public void setExpressionId(String expressionId) {
        this.expressionId = expressionId;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ServiceVersionId) ) return false;
		 ServiceVersionId castOther = ( ServiceVersionId ) other; 
         
		 return ( (this.getContractId()==castOther.getContractId()) || ( this.getContractId()!=null && castOther.getContractId()!=null && this.getContractId().equals(castOther.getContractId()) ) )
 && ( (this.getServiceName()==castOther.getServiceName()) || ( this.getServiceName()!=null && castOther.getServiceName()!=null && this.getServiceName().equals(castOther.getServiceName()) ) )
 && ( (this.getExpressionId()==castOther.getExpressionId()) || ( this.getExpressionId()!=null && castOther.getExpressionId()!=null && this.getExpressionId().equals(castOther.getExpressionId()) ) )
 && ( (this.getBeginDate()==castOther.getBeginDate()) || ( this.getBeginDate()!=null && castOther.getBeginDate()!=null && this.getBeginDate().equals(castOther.getBeginDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getContractId() == null ? 0 : this.getContractId().hashCode() );
         result = 37 * result + ( getServiceName() == null ? 0 : this.getServiceName().hashCode() );
         result = 37 * result + ( getExpressionId() == null ? 0 : this.getExpressionId().hashCode() );
         result = 37 * result + ( getBeginDate() == null ? 0 : this.getBeginDate().hashCode() );
         return result;
   }   


}


