package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * TaxCode generated by hbm2java
 */
public class TaxCode  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=8) private String taxCodeHeader;
     @Length(min=0, max=30) private String taxDescr;
     @Length(min=0, max=1) private String taxType;
     private Boolean includeVat;
     private Set<TaxCodeTaxRate> taxCodeTaxRates = new HashSet<TaxCodeTaxRate>(0);

     // Constructors

    /** default constructor */
    public TaxCode() {
    }

	/** minimal constructor */
    public TaxCode(String taxCodeHeader) {
        this.taxCodeHeader = taxCodeHeader;
    }
    /** full constructor */
    public TaxCode(String taxCodeHeader, String taxDescr, String taxType, Boolean includeVat, Set<TaxCodeTaxRate> taxCodeTaxRates) {
       this.taxCodeHeader = taxCodeHeader;
       this.taxDescr = taxDescr;
       this.taxType = taxType;
       this.includeVat = includeVat;
       this.taxCodeTaxRates = taxCodeTaxRates;
    }
   
    // Property accessors
    public String getTaxCodeHeader() {
        return this.taxCodeHeader;
    }
    
    public void setTaxCodeHeader(String taxCodeHeader) {
        this.taxCodeHeader = taxCodeHeader;
    }
    public String getTaxDescr() {
        return this.taxDescr;
    }
    
    public void setTaxDescr(String taxDescr) {
        this.taxDescr = taxDescr;
    }
    public String getTaxType() {
        return this.taxType;
    }
    
    public void setTaxType(String taxType) {
        this.taxType = taxType;
    }
    public Boolean getIncludeVat() {
        return this.includeVat;
    }
    
    public void setIncludeVat(Boolean includeVat) {
        this.includeVat = includeVat;
    }
    public Set<TaxCodeTaxRate> getTaxCodeTaxRates() {
        return this.taxCodeTaxRates;
    }
    
    public void setTaxCodeTaxRates(Set<TaxCodeTaxRate> taxCodeTaxRates) {
        this.taxCodeTaxRates = taxCodeTaxRates;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaxCode) ) return false;
		 TaxCode castOther = ( TaxCode ) other; 
         
		 return ( (this.getTaxCodeHeader()==castOther.getTaxCodeHeader()) || ( this.getTaxCodeHeader()!=null && castOther.getTaxCodeHeader()!=null && this.getTaxCodeHeader().equals(castOther.getTaxCodeHeader()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTaxCodeHeader() == null ? 0 : this.getTaxCodeHeader().hashCode() );
         
         
         
         
         return result;
   }   


}


