package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * TaxRate generated by hbm2java
 */
public class TaxRate  implements java.io.Serializable {

    // Fields    

     private TaxRateId taxRateId;
     @Length(min=0, max=128) private String description;
     @NotBlank @Length(min=0, max=1) private String taxType;
     private double taxPct;

     // Constructors

    /** default constructor */
    public TaxRate() {
    }

	/** minimal constructor */
    public TaxRate(TaxRateId taxRateId, String taxType) {
        this.taxRateId = taxRateId;
        this.taxType = taxType;
    }
    /** full constructor */
    public TaxRate(TaxRateId taxRateId, String description, String taxType, double taxPct) {
       this.taxRateId = taxRateId;
       this.description = description;
       this.taxType = taxType;
       this.taxPct = taxPct;
    }
   
    // Property accessors
    public TaxRateId getTaxRateId() {
        return this.taxRateId;
    }
    
    public void setTaxRateId(TaxRateId taxRateId) {
        this.taxRateId = taxRateId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getTaxType() {
        return this.taxType;
    }
    
    public void setTaxType(String taxType) {
        this.taxType = taxType;
    }
    public double getTaxPct() {
        return this.taxPct;
    }
    
    public void setTaxPct(double taxPct) {
        this.taxPct = taxPct;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaxRate) ) return false;
		 TaxRate castOther = ( TaxRate ) other; 
         
		 return ( (this.getTaxRateId()==castOther.getTaxRateId()) || ( this.getTaxRateId()!=null && castOther.getTaxRateId()!=null && this.getTaxRateId().equals(castOther.getTaxRateId()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) )
 && ( (this.getTaxType()==castOther.getTaxType()) || ( this.getTaxType()!=null && castOther.getTaxType()!=null && this.getTaxType().equals(castOther.getTaxType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTaxRateId() == null ? 0 : this.getTaxRateId().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         result = 37 * result + ( getTaxType() == null ? 0 : this.getTaxType().hashCode() );
         
         return result;
   }   


}


