package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * TestLanguage generated by hbm2java
 */
public class TestLanguage  implements java.io.Serializable {

    // Fields    

     private TestLanguageId testLanguageId;
     @Length(min=0, max=9) private String testDesc;

     // Constructors

    /** default constructor */
    public TestLanguage() {
    }

	/** minimal constructor */
    public TestLanguage(TestLanguageId testLanguageId) {
        this.testLanguageId = testLanguageId;
    }
    /** full constructor */
    public TestLanguage(TestLanguageId testLanguageId, String testDesc) {
       this.testLanguageId = testLanguageId;
       this.testDesc = testDesc;
    }
   
    // Property accessors
    public TestLanguageId getTestLanguageId() {
        return this.testLanguageId;
    }
    
    public void setTestLanguageId(TestLanguageId testLanguageId) {
        this.testLanguageId = testLanguageId;
    }
    public String getTestDesc() {
        return this.testDesc;
    }
    
    public void setTestDesc(String testDesc) {
        this.testDesc = testDesc;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TestLanguage) ) return false;
		 TestLanguage castOther = ( TestLanguage ) other; 
         
		 return ( (this.getTestLanguageId()==castOther.getTestLanguageId()) || ( this.getTestLanguageId()!=null && castOther.getTestLanguageId()!=null && this.getTestLanguageId().equals(castOther.getTestLanguageId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTestLanguageId() == null ? 0 : this.getTestLanguageId().hashCode() );
         
         return result;
   }   


}


