package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * TestDescriptionId generated by hbm2java
 */
public class TestDescriptionId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=96) private String testId;
     @NotBlank @Length(min=0, max=12) private String testDescriptionType;
     @NotBlank @Length(min=0, max=300) private String primaryDescription;
     @NotBlank @Length(min=0, max=300) private String secondDescription;

     // Constructors

    /** default constructor */
    public TestDescriptionId() {
    }

    /** full constructor */
    public TestDescriptionId(String testId, String testDescriptionType, String primaryDescription, String secondDescription) {
       this.testId = testId;
       this.testDescriptionType = testDescriptionType;
       this.primaryDescription = primaryDescription;
       this.secondDescription = secondDescription;
    }
   
    // Property accessors
    public String getTestId() {
        return this.testId;
    }
    
    public void setTestId(String testId) {
        this.testId = testId;
    }
    public String getTestDescriptionType() {
        return this.testDescriptionType;
    }
    
    public void setTestDescriptionType(String testDescriptionType) {
        this.testDescriptionType = testDescriptionType;
    }
    public String getPrimaryDescription() {
        return this.primaryDescription;
    }
    
    public void setPrimaryDescription(String primaryDescription) {
        this.primaryDescription = primaryDescription;
    }
    public String getSecondDescription() {
        return this.secondDescription;
    }
    
    public void setSecondDescription(String secondDescription) {
        this.secondDescription = secondDescription;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TestDescriptionId) ) return false;
		 TestDescriptionId castOther = ( TestDescriptionId ) other; 
         
		 return ( (this.getTestId()==castOther.getTestId()) || ( this.getTestId()!=null && castOther.getTestId()!=null && this.getTestId().equals(castOther.getTestId()) ) )
 && ( (this.getTestDescriptionType()==castOther.getTestDescriptionType()) || ( this.getTestDescriptionType()!=null && castOther.getTestDescriptionType()!=null && this.getTestDescriptionType().equals(castOther.getTestDescriptionType()) ) )
 && ( (this.getPrimaryDescription()==castOther.getPrimaryDescription()) || ( this.getPrimaryDescription()!=null && castOther.getPrimaryDescription()!=null && this.getPrimaryDescription().equals(castOther.getPrimaryDescription()) ) )
 && ( (this.getSecondDescription()==castOther.getSecondDescription()) || ( this.getSecondDescription()!=null && castOther.getSecondDescription()!=null && this.getSecondDescription().equals(castOther.getSecondDescription()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTestId() == null ? 0 : this.getTestId().hashCode() );
         result = 37 * result + ( getTestDescriptionType() == null ? 0 : this.getTestDescriptionType().hashCode() );
         result = 37 * result + ( getPrimaryDescription() == null ? 0 : this.getPrimaryDescription().hashCode() );
         result = 37 * result + ( getSecondDescription() == null ? 0 : this.getSecondDescription().hashCode() );
         return result;
   }   


}


