package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * TowingCompany generated by hbm2java
 */
public class TowingCompany  implements java.io.Serializable {

    // Fields    

     private long id;
     @NotBlank @Length(min=0, max=128) private String name;
     @Length(min=0, max=1) private String status;
     @Length(min=0, max=64) private String city;
     @Length(min=0, max=32) private String phone;
     @Email @Length(min=0, max=70) private String email;
     @Length(min=0, max=6) private String stateCode;
     @NotBlank @Length(min=0, max=3) private String countryCode;
     private Country country;
     private State state;

     // Constructors

    /** default constructor */
    public TowingCompany() {
    }

	/** minimal constructor */
    public TowingCompany(String countryCode) {
        this.countryCode = countryCode;
    }
    /** full constructor */
    public TowingCompany(String name, String status, String city, String phone, String email, String stateCode, String countryCode, Country country, State state) {
       this.name = name;
       this.status = status;
       this.city = city;
       this.phone = phone;
       this.email = email;
       this.stateCode = stateCode;
       this.countryCode = countryCode;
       this.country = country;
       this.state = state;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getStateCode() {
        return this.stateCode;
    }
    
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public State getState() {
        return this.state;
    }
    
    public void setState(State state) {
        this.state = state;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TowingCompany) ) return false;
		 TowingCompany castOther = ( TowingCompany ) other; 
         
		 return ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         
         
         
         
         
         
         
         
         return result;
   }   


}


