package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * UserLanguage generated by hbm2java
 */
public class UserLanguage  implements java.io.Serializable {

    // Fields    

     private UserLanguageId userLanguageId;
     private String customerServiceRep;
     private User user;

     // Constructors

    /** default constructor */
    public UserLanguage() {
    }

	/** minimal constructor */
    public UserLanguage(UserLanguageId userLanguageId) {
        this.userLanguageId = userLanguageId;
    }
    /** full constructor */
    public UserLanguage(UserLanguageId userLanguageId, String customerServiceRep, User user) {
       this.userLanguageId = userLanguageId;
       this.customerServiceRep = customerServiceRep;
       this.user = user;
    }
   
    // Property accessors
    public UserLanguageId getUserLanguageId() {
        return this.userLanguageId;
    }
    
    public void setUserLanguageId(UserLanguageId userLanguageId) {
        this.userLanguageId = userLanguageId;
    }
    public String getCustomerServiceRep() {
        return this.customerServiceRep;
    }
    
    public void setCustomerServiceRep(String customerServiceRep) {
        this.customerServiceRep = customerServiceRep;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserLanguage) ) return false;
		 UserLanguage castOther = ( UserLanguage ) other; 
         
		 return ( (this.getUserLanguageId()==castOther.getUserLanguageId()) || ( this.getUserLanguageId()!=null && castOther.getUserLanguageId()!=null && this.getUserLanguageId().equals(castOther.getUserLanguageId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserLanguageId() == null ? 0 : this.getUserLanguageId().hashCode() );
         
         
         return result;
   }   


}


