package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * UserLanguageId generated by hbm2java
 */
public class UserLanguageId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=128) private String loginName;
     @NotBlank @Length(min=0, max=9) private String languageCD;

     // Constructors

    /** default constructor */
    public UserLanguageId() {
    }

    /** full constructor */
    public UserLanguageId(String loginName, String languageCD) {
       this.loginName = loginName;
       this.languageCD = languageCD;
    }
   
    // Property accessors
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    public String getLanguageCD() {
        return this.languageCD;
    }
    
    public void setLanguageCD(String languageCD) {
        this.languageCD = languageCD;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserLanguageId) ) return false;
		 UserLanguageId castOther = ( UserLanguageId ) other; 
         
		 return ( (this.getLoginName()==castOther.getLoginName()) || ( this.getLoginName()!=null && castOther.getLoginName()!=null && this.getLoginName().equals(castOther.getLoginName()) ) )
 && ( (this.getLanguageCD()==castOther.getLanguageCD()) || ( this.getLanguageCD()!=null && castOther.getLanguageCD()!=null && this.getLanguageCD().equals(castOther.getLanguageCD()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLoginName() == null ? 0 : this.getLoginName().hashCode() );
         result = 37 * result + ( getLanguageCD() == null ? 0 : this.getLanguageCD().hashCode() );
         return result;
   }   


}


