package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * VesselTypeSet generated by hbm2java
 */
public class VesselTypeSet  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=45) private String vesselTypeSetName;
     private Boolean defaultFlag;

     // Constructors

    /** default constructor */
    public VesselTypeSet() {
    }

	/** minimal constructor */
    public VesselTypeSet(String vesselTypeSetName) {
        this.vesselTypeSetName = vesselTypeSetName;
    }
    /** full constructor */
    public VesselTypeSet(String vesselTypeSetName, Boolean defaultFlag) {
       this.vesselTypeSetName = vesselTypeSetName;
       this.defaultFlag = defaultFlag;
    }
   
    // Property accessors
    public String getVesselTypeSetName() {
        return this.vesselTypeSetName;
    }
    
    public void setVesselTypeSetName(String vesselTypeSetName) {
        this.vesselTypeSetName = vesselTypeSetName;
    }
    public Boolean getDefaultFlag() {
        return this.defaultFlag;
    }
    
    public void setDefaultFlag(Boolean defaultFlag) {
        this.defaultFlag = defaultFlag;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VesselTypeSet) ) return false;
		 VesselTypeSet castOther = ( VesselTypeSet ) other; 
         
		 return ( (this.getVesselTypeSetName()==castOther.getVesselTypeSetName()) || ( this.getVesselTypeSetName()!=null && castOther.getVesselTypeSetName()!=null && this.getVesselTypeSetName().equals(castOther.getVesselTypeSetName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getVesselTypeSetName() == null ? 0 : this.getVesselTypeSetName().hashCode() );
         
         return result;
   }   


}


