package com.intertek.entity;
// Generated by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * VesselTypeId generated by hbm2java
 */
public class VesselTypeId  implements java.io.Serializable {

    // Fields    

     @NotBlank @Length(min=0, max=45) private String vesselSet;
     @NotBlank @Length(min=0, max=45) private String vesselType;
     private Date beginDate;

     // Constructors

    /** default constructor */
    public VesselTypeId() {
    }

    /** full constructor */
    public VesselTypeId(String vesselSet, String vesselType, Date beginDate) {
       this.vesselSet = vesselSet;
       this.vesselType = vesselType;
       this.beginDate = beginDate;
    }
   
    // Property accessors
    public String getVesselSet() {
        return this.vesselSet;
    }
    
    public void setVesselSet(String vesselSet) {
        this.vesselSet = vesselSet;
    }
    public String getVesselType() {
        return this.vesselType;
    }
    
    public void setVesselType(String vesselType) {
        this.vesselType = vesselType;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VesselTypeId) ) return false;
		 VesselTypeId castOther = ( VesselTypeId ) other; 
         
		 return ( (this.getVesselSet()==castOther.getVesselSet()) || ( this.getVesselSet()!=null && castOther.getVesselSet()!=null && this.getVesselSet().equals(castOther.getVesselSet()) ) )
 && ( (this.getVesselType()==castOther.getVesselType()) || ( this.getVesselType()!=null && castOther.getVesselType()!=null && this.getVesselType().equals(castOther.getVesselType()) ) )
 && ( (this.getBeginDate()==castOther.getBeginDate()) || ( this.getBeginDate()!=null && castOther.getBeginDate()!=null && this.getBeginDate().equals(castOther.getBeginDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getVesselSet() == null ? 0 : this.getVesselSet().hashCode() );
         result = 37 * result + ( getVesselType() == null ? 0 : this.getVesselType().hashCode() );
         result = 37 * result + ( getBeginDate() == null ? 0 : this.getBeginDate().hashCode() );
         return result;
   }   


}


