package com.intertek.phoenix.entity;

// Generated by Hibernate Tools 3.2.0.beta8

import javax.persistence.Column;

import org.springmodules.validation.bean.conf.loader.annotation.handler.*;

/**
 * ConsolidatedInvoiceId generated by hbm2java
 */
public class ConsolidatedInvoiceId {

    // Fields

    @Column(name = "CONSOL_INVOICE", length=22)
    private String consolInvoiceNo;
    @Column(name = "BU_NAME", length=5)
    private String buName;

    // Constructors

    /** default constructor */
    public ConsolidatedInvoiceId() {
    }

    /** full constructor */
    public ConsolidatedInvoiceId(String consolInvoiceNo, String buName) {
        this.consolInvoiceNo = consolInvoiceNo;
        this.buName = buName;
    }

    // Property accessors
    public String getConsolInvoiceNo() {
        return this.consolInvoiceNo;
    }

    public void setConsolInvoiceNo(String consolInvoiceNo) {
        this.consolInvoiceNo = consolInvoiceNo;
    }

    public String getBuName() {
        return this.buName;
    }

    public void setBuName(String buName) {
        this.buName = buName;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ConsolidatedInvoiceId))
            return false;
        ConsolidatedInvoiceId castOther = (ConsolidatedInvoiceId) other;

        return ((this.getConsolInvoiceNo() == castOther.getConsolInvoiceNo()) || (this.getConsolInvoiceNo() != null && castOther.getConsolInvoiceNo() != null && this
                .getConsolInvoiceNo().equals(castOther.getConsolInvoiceNo())))
               && ((this.getBuName() == castOther.getBuName()) || (this.getBuName() != null && castOther.getBuName() != null && this.getBuName()
                       .equals(castOther.getBuName())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getConsolInvoiceNo() == null ? 0 : this.getConsolInvoiceNo().hashCode());
        result = 37 * result + (getBuName() == null ? 0 : this.getBuName().hashCode());
        return result;
    }

}
